### ISSUE TITLE
Unchecked checkbox show up as checked

### ISSUE THREAD

**Issue by sjordan1975** [vue-generators/vue-form-generator#179]
I have the following schema for checkbox:
```
{
type: "checkbox",
label: "Terms and Conditions",
model: "terms",
default: false
}
```

When I save the form, it posts the string "false" to the server.

So when the data is read from the server and the response is assigned to the model (ex. when editing an existing form), the component interprets "false" as truthy (strings are truthy) and makes the checkbox ticked.

**Comment by cristijora** [comment]
Can't you post `false` as a bool value to the server? Why send it as a string? It would solve all the issues.
Checkboxes need boolean values to work

**Comment by sjordan1975** [comment]
@cristijora it has nothing to do with posting as a bool to the server. ajax posts are always sent as strings. For example see http://stackoverflow.com/questions/3654454/boolean-variables-posted-through-ajax-being-treated-as-strings-in-server-side

The point of my post was that I would expect the component to handle checkbox values are either true or false values internal to the component. When a response is received from the server; the component would recognize that the values matches a checkbox schema and cast values accordingly. I can of course my code cast the value of "false" to false and "true" to true, but again, I would think that as a component the has a checkbox model it would be existing functionality

**Comment by icebob** [comment]
I think this convertion is not part of vfg, you should convert these bool values in your code.

**Comment by hansi90** [comment]
You can define a "get" method in schema, where you can convert the model value.

```js
{
    type: "checkbox",
    label: "Checkbox",
    model: "status",
    inputName :"checkname",
    get(model) {
        if (model){
            if (isString(model.status))
                return model.status === "true" ? true : false;
            
            return model.status;
        }
    }
}
```

**Comment by sjordan1975** [comment]
@icebob I have to respectfully disagree with you because of the "type" checkbox. 

If in the schema I define the model to be a checkbox, then by definition, the semantics of the model means it **must** be a boolean. IMO, the component should respect that assertion. 

In engineering it's referred to as [The Law of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment): "...a component of a system should behave in a manner consistent with how users of that component are likely to expect it to behave"

**Comment by lionel-bijaoui** [comment]
@sjordan1975 You are welcome to implement the result of your philosophical software design/development discussion into a PR.
In the meantime, I'm closing this issue.
