### ISSUE TITLE
optgroup for select

### ISSUE THREAD

**Issue by jmverges** [vue-generators/vue-form-generator#214]
Hi guys,

what do you think about having the possibility to have optgroup in a select field?

Cheers

**Comment by dflock** [comment]
Sounds like a good idea - it's a supported feature in (at least) HTML 4 & 5 selects, so i would be in favour of supporting it.

The changes to the schema and the template of the select component would be pretty similar to the changes for the Grouping feature (#209) - which I'm sure you're aware, as you wrote a lot of it ;)

**Comment by icebob** [comment]
I support it. PR welcome :)

**Comment by amans2k** [comment]
Hello Guys,

First of all a great library. Using it, in most projects.
One thing came across today, where I need to use optgroup in select.
Then found this issue.
Can anyone share the jsfiddle example of select with optgroup?

Thanks in advance.

**Comment by zoul0813** [comment]
Closing - optgroup was implemented at an unknown point in time.

```
{
  type: "select",
  values: [
    {
      "name": "foo",
      "id": "bar",
      "group": "Foobar"
    },
    {
      "name": "Bar",
      "id": "foo",
      "group": "Bar"
    }
  ]
}
```
