### ISSUE TITLE
Render groups as bootstrap tabs

### ISSUE THREAD

**Issue by ericpyle** [vue-generators/vue-form-generator#285]
Wishing I could use groups to render the form in a different way, like with each section having it's own tab. I could have multiple vfg instances with one form per tab. Or maybe I could use multi attribute to just hide all fields that are not in that tab. 

Thoughts on best way to do this?

**Comment by ericpyle** [comment]
Or use visibility function that can somehow determine which tab is in use?

**Comment by DelfsEngineering** [comment]
This works great:
Take your source schema and insert a function for the `visibility` field key's value

So if you want to show/hide field(s) based on the value of another field set their visibility to a function like 

```
function(){
   return this.model.fieldA == 'someValue'
}
```

of course use what ever logic you want now.

**Comment by DelfsEngineering** [comment]
For tabs see `vue-form-wizard` here https://github.com/cristijora/vue-form-wizard

**Comment by ericpyle** [comment]
@DelfsEngineering thanks so much for the suggestions! I'll definitely take a harder look at the vue-form-wizard.  Know of any examples of how to make the tabs look like regular bootstrap tabs?  It's possible that I could rethink whether my app should have more of a guided wizard UX, but converting my app over to how it currently works would be great.

**Comment by ericpyle** [comment]
@DelfsEngineering also, do you know of any examples of how the multi field and multiple option is used in practice? I see what the documentation says, but I suspect there's a use-case or use-cases behind supporting that and the merge logic that respects multi.  Thanks again for any help!

**Comment by DelfsEngineering** [comment]
I suppose the best you could do without forking `vue-form-wizard` is some injected CSS, or hacking the accompanying CSS.

**Comment by cristijora** [comment]
Hey @ericpyle 
For tabs 
https://github.com/spatie/vue-tabs-component
https://github.com/cristijora/vue-tabs

For a more strict flow/wizard
https://github.com/cristijora/vue-form-wizard
The wizard supports tab layout, however they do not act like tabs since the wizard has a stricter validation flow (e.g you can't click a tab unless it was visited and validated)
https://jsfiddle.net/bt5dhqtf/99/

If you need tabs use tab components, if you need a strict validation flow use the wizard. Both tabs and the wizard should work fine with form-generator.

**Comment by ericpyle** [comment]
Thanks, @cristijora. I'll look into integrating vfg with the other tab components and also ask my team whether we want to move toward a wizard approach.

@DelfsEngineering I still have an outstanding question about use cases for `multi` and `multiple` in vfg, if anyone cares to share?

**Comment by cristijora** [comment]
@ericpyle you mean multi select ?

**Comment by ericpyle** [comment]
I mean multi field property "if true, it will visible only if multiple is true in component attributes" https://icebob.gitbooks.io/vueformgenerator/content/fields/field_properties.html

**Comment by ericpyle** [comment]
@cristijora see reply above. Thanks!

**Comment by cristijora** [comment]
@ericpyle Honestly not sure to what it refers. I've used the `multiple` property only on multi-select field which has [vue-multi-select](http://monterail.github.io/vue-multiselect/) behind it.
Maybe @icebob could answer to this.

**Comment by ericpyle** [comment]
as far as this issue goes, I'm ready to close it. I think if needed, I could have one vfg instance that gets reloaded each time a user switches tabs.

@icebob before I close this, could you please explain what the `multi` field property is used for in conjunction with `multiple` vfg option? I've seen the documentation, but I haven't seen working examples to help me understand what it's used for

**Comment by zoul0813** [comment]
@ericpyle can we close this?

**Comment by ericpyle** [comment]
@zoul0813 yes

**Comment by timoteo7** [comment]
hey @cristijora
using : 
https://github.com/cristijora/vue-tabs

is there any easy way (or if it is possible) to convert the `fieldset` (from the `group` scheme) to v-tab?

some as in the example of this subgroup ('Location') in #670

![tabs](https://user-images.githubusercontent.com/611996/79669418-ef5f0400-8180-11ea-9ff0-4bf63c56673c.png)
