### ISSUE TITLE
how to make page break

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [vue-generators/vue-form-generator#299]
Hello
how do you create different regions of fields equal to a page break

it's possible?

**Comment by DelfsEngineering** [comment]
I created a clearfix custom component for bootstrap css but I would also like to know what best practices are.

**Comment by icebob** [comment]
Please explain and create a fiddle.

**Comment by DelfsEngineering** [comment]
This is my clearfix.vue custom component. I use it and build forms dynamically. When the for designer needs to add a horizontal break they can simply use 'clearfix' as the component type.

```
// Custom VFG components
// ClearFix.vue
<template>
        <div class="clearfix"></div>
</template>
 
<script>
    module.exports = {
        props: ['text'],
        name: 'clearfix',
        mixins: [VueFormGenerator.abstractField],
        methods: {

        },
        data() {
            return {}
        }
    }
</script>

<style>
   .field-clearfix  {
        height: 0px;
        margin-bottom: 0px !important;
    }
</style>

```
