### ISSUE TITLE
Two way data binding on forms?

### ISSUE THREAD

**Issue by sayhitoarvind** [vue-generators/vue-form-generator#323]
Hi,
I'm trying to achieve two way data binding using v-model on form elements? How can this be achieved?
Thanks

**Comment by ChadTaljaardt** [comment]
What specifically are you trying to do?

**Comment by sayhitoarvind** [comment]
I need to update the form's data frequently in my application

**Comment by zoul0813** [comment]
@sayhitoarvind I'm closing this issue, if you'd like to re-open it please provide detailed information on what you are attempting to achieve and a working JSFiddle detailing your problem.

VFG supports a 'model-updated' event which is fired whenever a form model is changed.
