### ISSUE TITLE
Add Dynamic Value in type select or multiselect 

### ISSUE THREAD

**Issue by keyurptl** [vue-generators/vue-form-generator#324]
Thanks for such great plugin.

I have question how can i assign value in select or vue multiselect  dynamic variable I mean Like this 
```
type: "select",
        label: "countries",
        model: "countries",
		values : this.countries,
		options : this.countries
```

This way how can i use "countries"  array to assign inside filed. If I am adding static array it works perfect.

**Comment by icebob** [comment]
Hi,

fiddle example: https://jsfiddle.net/icebob/0mg1v81e/872/

**Comment by keyurptl** [comment]
Thanks for your response.  But bit more In my case.
This 
```
let countries = [];
return{
		countries: countries,
}
 getCountries: function(){
			axios.get('/country').then(response => {
                    this.countries = response.data;
        	});
        },
```
In this case it display as blank, I mean not displaying any value in select box.

**Comment by keyurptl** [comment]
Hello Any update for above query ?

**Comment by hotrush** [comment]
@icebob required not working for select field in your example. Check this please https://jsfiddle.net/0mg1v81e/929/

**Comment by SebastienTainon** [comment]
I've made a Multiselect custom field that works with async calls for vue-form-generator, see this gist with an example of use: https://gist.github.com/SebastienTainon/7d3add17452f36fda3636835a729bb4e

**Comment by goors** [comment]
@hotrush required not working for select. were you able to solve it?

**Comment by lsrr** [comment]
@goors Seems like you didn't get an answer from @hotrush . Did you solve it or does the issue still exist?

**Comment by zoul0813** [comment]
The solution to this is using a function for the `values`,

```
{
  type: "select",
  model: "country",
  values: () => {
    return this.countries;
  }
}
```

[Sample Fiddle](https://jsfiddle.net/q8epkg0c/)

**Comment by Yuri47h** [comment]
> The solution to this is using a function for the `values`,
> 
> ```
> {
>   type: "select",
>   model: "country",
>   values: () => {
>     return this.countries;
>   }
> }
> ```
> 
> [Sample Fiddle](https://jsfiddle.net/q8epkg0c/)
Hi! This example does not work for me. I use Typescript class-based component
