### ISSUE TITLE
The computed property "errors" is already defined in data.

### ISSUE THREAD

**Issue by argueta15** [vue-generators/vue-form-generator#326]
![image](https://user-images.githubusercontent.com/17033669/32138068-5cf6c3ce-bbf2-11e7-84fc-3867a0e841e5.png)

**Comment by zoul0813** [comment]
@argueta15 can you provide a JSFiddle that reproduces this issue?

**Comment by lwolter** [comment]
I have got the same error:
```
[Vue warn]: The computed property "errors" is already defined in data.

found in

---> <FieldInput>
       <VueFormGenerator>
         <VueJsModal> at /Users/yev.vlasenko2/Projects/vue/vue-js-modal/src/Modal.vue
           <ExcelReportFilter> at src/components/excelReport/ExcelReportFilter.vue
             <CreateExcelReport> at src/components/excelReport/CreateExcelReport.vue

```

**Comment by lwolter** [comment]
Problem solved with:

Vue.use(VeeValidate, {
  errorBagName: 'vErrors'
});

**Comment by sl0wik** [comment]
In my case issue was resolved with:
```
Vue.use(require('vee-validate'), { inject: false });
```
Is there any alternative that won't require adjusting all my components using veevalidate?

**Comment by iurquiza** [comment]
Providing the ability to rename the error prop when initializing the form generator component in the same way vee-validate does would be ideal. ```Vue.use(VueFormGenerator, { errorBagName: 'vErrors'});```

**Comment by yavand** [comment]
Hi guys,
I get this error in vee-validate `"vee-validate": "^3.0.11"`

```
[Vue warn]: The computed property "errors" is already defined in data.

found in

---> <ValidationObserver>
       <LoginForm> at components/auth/forms/login_form.vue
         <Pages/auth/login.vue> at pages/auth/login.vue
           <Nuxt>
             <Layouts/auth.vue> at layouts/auth.vue
               <Root>
```
please help me to resolving this issue. thanks
