### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by espositodaniele** [vue-generators/vue-form-generator#329]
Hello,

I would like to if it's possible to use this fantastic package with JSON Schema,

>  http://json-schema.org/

I gave a look at JSON type used for the fields, it seems different. Can anyone help with this?

I will appreciate.
Thanks.

D

**Comment by zoul0813** [comment]
What are you trying to accomplish?

**Comment by zoul0813** [comment]
Closing this issue, if you'd like to re-open it please provide more detail about your request.  Thanks.

**Comment by felubra** [comment]
I think that @espositodaniele was trying to use the JSON Schema specification to define the fields, instead of using the 'proprietary' schema of this component. Somewhat the way [vue-json-schema](https://github.com/demsking/vue-json-schema) does.
I am currently interested in doing the same thing. Maybe a translation function between schemas will do, but the JSON Schema spec does not account for all the particularities of a HTML form, eg: there is no inputType field in the spec. I am thinking about problem.

**Comment by zoul0813** [comment]
_Just my "two cents" on the subject..._

JSON Schema is meant for defining what an object should look like, so you can validate a JSON Object against a strict schema.  It's not intended to be used as a "go to" format for creating objects.

In the case of VFG, the schema passed to the form is specific to VFG and isn't compatible with other projects (currently) ... JSON Schema would just add bloat and unnecessary depth to the schema object passed to VFG while providing no benefits over what is currently being used.

VFG uses the "schema" being passed in as what is referred to in JSON Schema as an "instance" (the object being validated against the json schema).  JSON schema itself has no defined "format" for generating forms, so converting the existing schema object into a json schema definition would just increase the size of the schema document and the bandwidth needed to transport it, as well as complicate the creation and use of the schema object.

If we added support for JSON Schema, it would likely be in the form of a schema document that we make public so you could use that schema document to validate your schema object before passing it to VFG (I will likely be creating one in the next couple months as my VFG forms are fed from an API which uses JSON schema to validate inbound/outbound requests).  VFG could also use that schema document to validate the schema object you passed to VFG before attempting to use it (ie; making sure all fields had a "type" and "model" associated with them), however, this would likely be an optional feature that you'd have to enable explicitly and ensure you included the necessary dependencies so as not to bloat the core VFG distribution with JSON Schema validation code.

I do believe we need a "cleaner" looking schema though, and we may address this in v3 ... but I don't expect the schema to use the JSON Schema format as that's not what JSON Schema is intended for.

**Comment by DelfsEngineering** [comment]
I don't see a need to validate the schema that defines a form. I use VFG in a highly dynamic way where users generate the schema. I think if validation is needed, then you would be a different concern that precedes the JSON hitting VFG.
