### ISSUE TITLE
Masked input not updating model

### ISSUE THREAD

**Issue by nsbuckner** [vue-generators/vue-form-generator#335]
I have a simple form where I'm trying to add a masked input. The mask is being applied to the input element, but when you change the value on that input it is not getting bound to the model. All other inputs on the page update the model on change. Is there something I'm missing in my schema to get the masked field to update properly?

[Here is a JSFiddle showing how this isn't working](https://jsfiddle.net/nsbuckner/wq13rLh4/1/). Notice the model does not update when you change the SSN input.

**Comment by WapiMukki** [comment]
i have the same problem.

**Comment by nsbuckner** [comment]
We ended up using cleave instead. You can do masking with it and it works, so I'd suggest it in the meantime.

**Comment by jonnycraze** [comment]
How did you do masking with cleave? @nsbuckner

**Comment by nsbuckner** [comment]
@jonnycraze Depends on what you need to do...but I was making a demo SSN input so I used a delimiter with blocks set to numeric only. 

For the form schema it was something like:
`{
                type: "cleave",
                label: "SSN",
                model: "SSN",
                pattern: "^\\d{9}|\\d{3}-\\d{2}-\\d{4}$",
                validator: VueFormGenerator.validators.regexp,
                cleaveOptions: {
                    numericOnly: true,
                    delimiters: ['-'],
                    blocks: [3, 2, 4]
                }
            }`

See the Delimiter demos at the bottom of the page here here: https://nosir.github.io/cleave.js/

**Comment by jonnycraze** [comment]
That is awesome, thank you @nsbuckner . one more question if you have the time, how do you import cleave to work with vue-form-generator. I'm getting an error and I'm assuming it's something simple i'm overlooking.

**Comment by nsbuckner** [comment]
@jonnycraze It's been a few months since I set up that demo project when I was testing out the form generator. I don't remember having to do anything special, just installed through NPM and then imported cleave into my boot.ts file:

`import 'cleave.js';`
`import 'cleave.js/dist/addons/cleave-phone.us.js'; //US Phone Numbers Addon`

There's install instructions here too that should cover it: https://github.com/nosir/cleave.js

**Comment by birdy247** [comment]
I am also facing this issue.  It seems like its only 1 way data binding i.e. If I set the model via dev tools, it updates, but if I change the test in the masked input, the model does not update.  I can see the component is using v-model="value".  Perhpas it needs to be found to value and emit the value when it changes?

**Comment by zoul0813** [comment]
Closing - reference #502 

Masked Input component will be removed in v3, the library it is based on is now defunct and no longer supported.
