### ISSUE TITLE
How can i change schema reactive? I want to change number input max attribute

### ISSUE THREAD

**Issue by dastiw1** [vue-generators/vue-form-generator#343]
How can i change schema reactive? I want to change number input max attribute.
I need to set one filed max attribute equal to another readonly input value

**Comment by zoul0813** [comment]
@dastiw1 - the schema is already a reactive object, if you update the value of an item within the schema it will be reflected within the form.

Closing this issue - if you feel this information is incorrect, please provide more detail (such as a working JSFiddle detailing your attempt).
