### ISSUE TITLE
Value of number type input

### ISSUE THREAD

**Issue by YgamiLight** [vue-generators/vue-form-generator#361]
I saw the way of getting value of a number type input is using "this.value".
And problems happened:
when the user enter  like this "10e10",this will be OK
But when they continue to type just like this "10e10ee.12e12e12e.12e21e".Obviously,this input is not a valid number,but the "this.value" equals to the Empty string,And looks like you guys converted the string to number.So the empty string will be converted to 0. And if we set a negative min/max value,the “10e10ee.12e12e12e.12e21e” will be passed, because 0 is greater than negative value.This is not what we expect.So maybe you can use the "this.valueAsNumber".In this way,the "10e10ee.12e12e12e.12e21e" will be pasred to NaN .And we can handle the error condition more  clearly .

**Comment by zoul0813** [comment]
@YgamiLight can you check out PR #363 and let me know if this will solve the issue you're reporting? It uses the same debounced format logic I introduced yesterday for date/datetime inputs to allow users to enter valid values into the HTML5 inputs and it looks at `valueAsNumber` for the input element of number/range inputs per your suggestion.

The model will have the value `NaN` stored on it, but this will be translated to `null` when converted to JSON as JSON does not support NaN/Infinity ...

**Comment by YgamiLight** [comment]
Fixed,thank you
