### ISSUE TITLE
Improve the integer validator

### ISSUE THREAD

**Issue by YgamiLight** [vue-generators/vue-form-generator#362]
When I want to use integer validator and min/max attribute together,the min/max will not work.And I checked the integer validator,found there is no relevant field.min and field.max code,Could you please add   it in integer validator?

**Comment by zoul0813** [comment]
@YgamiLight can you review PR #364 and let me know if that closes this issue?

**Comment by YgamiLight** [comment]
Fixed,I think.Thank you!

**Comment by zoul0813** [comment]
You think?
