### ISSUE TITLE
Custom field: International Telephone Input

### ISSUE THREAD

**Issue by iamstevendao** [vue-generators/vue-form-generator#368]
Please check out my form input. 
I tested to integrate with vue-form-generator.
I would be really awesome if you guys put it as one of the fields

my package:
https://www.npmjs.com/package/vue-tel-input

**Comment by ChadTaljaardt** [comment]
You should create a pull request adding this to the optional fields available.

**Comment by zoul0813** [comment]
I would recommend just building this out as a separate package.  I'm hoping that with v3 we will be removing the optional fields from the main code and breaking them out into separate packages ... this way, you don't have to have X, Y and Z optional fields enabled just because you want to use A, B and D optional fields.  Most of the optional fields also have extra dependencies, which can be handled in the optional fields package removing the need for you to make sure they are installed.

We can very likely add a link to this project in the docs ... @icebob ?

**Comment by icebob** [comment]
Yes, we can add it to the docs as 3rd party field.

**Comment by ChadTaljaardt** [comment]
In the mean time why not allow it as a optional field until V3 is out, if there is a pull request. 

Whats the ETA for V3?

**Comment by zoul0813** [comment]
v3 is being actively worked on, and I don't think we have any timelines for it.  

Adding more stuff to v2 just clutters it up.  If your package can be installed separately, that would be preferred as it would then be truly "optional".  It also allows the code to be maintained by you, without requiring the VFG team to review and approve changes to it as well as handle any issues being reported about it which just slows down our progress on v3 development and existing v2 issues.

Thanks for the contribution, the package looks promising from what I saw on npmjs.com

**Comment by iamstevendao** [comment]
Thanks guys for such a great work!
I am using this package as a custom field of VFG in my company's project so I was about to make it support VFG as default for everyone. But I do understand your thoughts so I will make a more detailed document for using it as a custom field of VFG in the README. And it would be awesome if this package has a chance to be in your docs.

**Comment by ChadTaljaardt** [comment]
Thanks for your work @iamstevendao 

I require this so im looking forward to seeing the implementation!

**Comment by zoul0813** [comment]
@lionel-bijaoui this project does not seem to support VFG anymore, should we remove it from the README.md?  It looks like the project is now a stand-alone custom component for Vue, and does not have any VFG support in it ... all references to VFG were removed from the projects README as well.

**Comment by iamstevendao** [comment]
Hi guys, I just added the usage for using `vue-tel-input` along with `vue-form-generator` back to README. https://github.com/EducationLink/vue-tel-input#use-as-a-custom-field-of-vue-form-generator.
It should not be a problem anymore right? @zoul0813
