### ISSUE TITLE
Question on overriding Styling (css)

### ISSUE THREAD

**Issue by jonnycraze** [vue-generators/vue-form-generator#369]
I have a general question, what is the recommended approach to overriding the styles that are shipped with Vue-Form-Generator?

I am evaluating VFG and would like to know what the best/accepted approach is for styling a form with my own styles, or with another frameworks styles (boostrap, material, pure, ect).

Thanks very much.

**Comment by zoul0813** [comment]
For the most part, the style classes used are mostly compatible with Bootstrap.  I don’t include the VFG css file and just implement whatever classes I need for custom styling.  V3 should have a cleaner interface for this, allowing you to override more style classes.  As is, v2 supports overriding style classes used in most of the higher level elements.

**Comment by jonnycraze** [comment]
Awesome, thanks for the quick reply @zoul0813 .
