### ISSUE TITLE
Using Cleave

### ISSUE THREAD

**Issue by jonnycraze** [vue-generators/vue-form-generator#371]
I'm sure I'm missing something obvious here, but I'm unclear how to implement cleave.

I have imported the asset, and created the field but i receive the following error:
``` Unknown custom element: <field-cleave> - did you register the component correctly? ```

Again, I'm sure I'm missing something simple but if anyone could chime in how to use the cleave input I would be very appreciative.

**Comment by jonnycraze** [comment]
Closing, I used core instead of full. problem solved.

**Comment by jewbetcha** [comment]
@jonnycraze could you elaborate on how you fixed this? I'm also having trouble getting it going.
