### ISSUE TITLE
custom field with integrated validator

### ISSUE THREAD

**Issue by fabifabi** [vue-generators/vue-form-generator#374]
thanks for this library for begin !

I want translate element ( http://element.eleme.io/#/en-US ) in your library.
This lib is for me far more good&beautifull than bootstrap :)

btw,i want element don't do email etc field....

So let's mix the two !

But for my email (it is example,i want translate all field), how validate it....without extra validator?

I means,i want my email be valdiate by the custom field,not by settings the validator 'in hard' in the schema....

i.e, now i have:
 {
            type: "email",
            label: "E-mail",
            model: "email",
            placeholder: "User's e-mail address",
            validator: VueFormGenerator.validators.email
          },

i want the field be validated without but the vaildator, more easy for the customer (who want say email is an email twice? )

How i can do it in a good way ?

I can watch the value? it is a good practice for it ?

Thanks for all your help.

**Comment by zoul0813** [comment]
If you’re creating a custom field, you can just hard core the email validator into it ... I’d recommend merging or testing if a validator was passed in the schema as opposed to just over writing the passed in validator “just in case” there’s a special use case (regex testing the TLD?).

Just add the email validator in the components “mount” event method.

**Comment by zoul0813** [comment]
@fabifabi closing this issue for now, feel free to re-open it if you need further assistance.
