### ISSUE TITLE
Cleave plugin worked incorrectly

### ISSUE THREAD

**Issue by YgamiLight** [vue-generators/vue-form-generator#376]
https://jsfiddle.net/YagamiLight/7naqyerk/1/
Here is the bug: The number separator should be the comma ','  instead of space  ' '. And I think it is better to set the value model to be pure number instead of the direct value of input which has comma or space

**Comment by zoul0813** [comment]
Not quite sure what you're showing here.  The delimiter used really depends on your locale, and it looks like the person who developed the cleave field lives in an area where " " is the common delimiter. The comma is commonly used as the decimal separator in a lot of locales, for example.  Here's a link with some common number formats for various locales: https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

You can easily change this by setting the delimiter in the cleaveOptions.  If anything, I think it would be good to have some sort of "global options" available as most of these options would be shared across multiple cleave fields in the same form ... however, this is easily handled by creating a shared function that returns a merged array of parameters passed in with a set of common/global parameters for cleave ... then just set the "cleaveOptions" property in the schema to the return value of the function.

As for storing the raw value in the object, this is not how VFG works... I don't believe any of the fields store raw values, and instead, always store the formatted values.  Having two different formats for display and storage would be a nice option for v3 though.

**Comment by YgamiLight** [comment]
Sorry, maybe I didn't express exactly.Here I want my number to be formatted in money format. And in the cleaveOptions I used the (numeralThousandsGroupStyle: 'thousand') key-value.But the formatted result is not I want.What I want is "123,456",but got "123 456"

**Comment by zoul0813** [comment]
You need to change the "delimiter" property in cleaveOptions, as I described above.

numeralThousandsGroupStyle does not determine whether or not to use "," or " " ... it only determines what a "thousand" is ... 

https://github.com/nosir/cleave.js/blob/master/doc/options.md#numeralthousandsgroupstyle

https://github.com/nosir/cleave.js/blob/master/doc/options.md#delimiter

**Comment by YgamiLight** [comment]
Thank you! This issue can be closed. Once again, Thanks very much.
