### ISSUE TITLE
Question: Does VFG support deep array binding

### ISSUE THREAD

**Issue by jonnycraze** [vue-generators/vue-form-generator#377]
I'm currently building a group, and binding each model to an array object key, like so:
```
groups: [
            {
              legend: "Categories",
              fields: [
                {
                  type: 'input',
                  inputType: 'text',
                  label: 'Category',
                  model: 'model.categories[0].name'
                },
                {
                  type: 'input',
                  inputType: 'text',
                  label: 'Slug',
                  model: 'model.categories[0].slug'
                }
              ]
            }
          ]
```

When the input field is changed, the updated value does not seem to bubble out to the model, I'm curious if this functionality is supported, or if I'm trying to do something that is not currently supported.

Thank you!

**Comment by zoul0813** [comment]
Can you provide a JSFiddle?

**Comment by jonnycraze** [comment]
Sure, let me set one up. My initial messaging is incorrect, the above example works, where i am struggling is using the model with a json pointer syntax
```
model: '/categories[0]["/value"]'
```

**Comment by zoul0813** [comment]
VFG doesn't support that type of model path.  VFG basically just takes the string passed to the model property and breaks it up using the '.' (dot) creating an object ... 

`model: 'categories[0].value'` would become `{ "categories[0]": { value: 'value' } }`

Check out the 'setModelValueByPath` method in VFG's abstractField ... 

```
		setModelValueByPath(path, value) {
			// convert array indexes to properties
			let s = path.replace(/\[(\w+)\]/g, ".$1");

			// strip a leading dot
			s = s.replace(/^\./, "");

			let o = this.model;
			const a = s.split(".");
			let i = 0;
			const n = a.length;
			while (i < n) {
				let k = a[i];
				if (i < n - 1)
					if (o[k] !== undefined) {
						// Found parent property. Step in
						o = o[k];
					} else {
						// Create missing property (new level)
						this.$root.$set(o, k, {});
						o = o[k];
					}
				else {
					// Set final property value
					this.$root.$set(o, k, value);
					return;
				}

				++i;
			}
		},
```
VFG uses Lodash internally for various purposes, so hopefully we can support lodash paths in the model as part of v3.

**Comment by jonnycraze** [comment]
Ah that answers that question, that would be an excellent feature. 
Thank you for your prompt response, I appreciate it.
