### ISSUE TITLE
Is there a way to use a basic multiselect field?

### ISSUE THREAD

**Issue by rDr4g0n** [vue-generators/vue-form-generator#378]
I see that there is support for vue-multiselect, but I need a basic `<select multiple></select>` type field that binds to an array of values rather than a single value. Is this currently possible? If not, is this a feature that can be added?

Thanks

**Comment by rDr4g0n** [comment]
Oh, I've just discovered your [custom fields](https://icebob.gitbooks.io/vueformgenerator/content/fields/custom_fields.html) documentation, which should solve this problem.  

However, it may be a useful default field!

**Comment by dflock** [comment]
There's a select field built in: https://icebob.gitbooks.io/vueformgenerator/content/fields/select.html

**Comment by rDr4g0n** [comment]
@dflock I specifically need a multiselect and I don't see a config option there to enable multiselect. I did copy that select field code and create a custom field which adds the `multiple` attribute to the `select` tag.
