### ISSUE TITLE
Custom tag and classes for groups not working - getting fieldset as a wrapper

### ISSUE THREAD

**Issue by ianshade** [vue-generators/vue-form-generator#379]
Hi, thanks for an awesome component!

I encountered a problem with the `tag=""` directive and `styleClasses` when using groups. Basically they are not working for me. When using `tag="div"` non-grouped fields are correctly wrapped in a div, but all groups are still in fieldsets and don't have styleClasses applied.

I reproduced the issue modifying the demo fiddle (vue@2.2.1, vue-form-generator@2.1.1): https://jsfiddle.net/ianshade/LLfrnequ/2/ 
Three non-grouped fields are in a div, but the groups below are in fieldsets and don't have style classes.

**Comment by zoul0813** [comment]
It looks like the package you are using isn't up-to-date with the latest code on GitHub.

I've updated your JSFiddle and pointed it at the current vfg.js in the repo, and it works as expected.

https://jsfiddle.net/LLfrnequ/3/

Update your package.json to pull VFG from GitHub, similar to this:

```
"vue-form-generator": "git+https://github.com/vue-generators/vue-form-generator.git#master",
```

**Comment by icebob** [comment]
@zoul0813  It's a manual process. Do I it now from the master?

**Comment by icebob** [comment]
I released a new version: https://github.com/vue-generators/vue-form-generator/releases/tag/v2.2.0

**Comment by ianshade** [comment]
Thanks a lot guys! I've been using npm and I didn't notice these changes in repo.
