### ISSUE TITLE
Set slot with VueMultiSelect

### ISSUE THREAD

**Issue by onhernandes** [vue-generators/vue-form-generator#380]
I'm using vueMultiSelect and there's an entry for `slot` to set the label for `not found`, but I can't set this through `vue-form-generator`. Does anyone knows how to set this?

**Comment by zoul0813** [comment]
Current list of supported Parma’s passed to the multiselect component are found here:

https://github.com/vue-generators/vue-form-generator/blob/master/src/fields/optional/fieldVueMultiSelect.vue

It’s possible not all options are available.

**Comment by timoteo7** [comment]
Thanks for the list of parameters,
I will record parameters that I tried, if others are doing the same as me:

`openDirection:'top' // ['bottom']`
