### ISSUE TITLE
Align Multiple inputs horizontally

### ISSUE THREAD

**Issue by gsitgithub** [vue-generators/vue-form-generator#384]
Currently all field inputs are vertically alligned. Even if I add **schema.fieldClasses**: 'col-md-4' and **schema. styleClasses**: 'col-md-3', width of field input doesn't change. 
I found that css class .vue-form-generator .form-group has width: 100% which is not effected by **schema. styleClasses** and **schema.fieldClasses**. 
Ofcourse field should be of width 100% if style classes are not provided. 

Currently I am using work-around for this by **removing** "width:100%" from class `vue-form-generator .form-group` and adding rule `form-group:not([class*=" col-"]){width:100%}`. It could be helpful for horizontal inputs.

**Comment by zoul0813** [comment]
If you're using Bootstrap, I would recommend removing the VFG CSS from your project all together as the majority of VFG's classes are Bootstrap compatible.  You may need to provide a handful of CSS yourself for certain field types though.

Here's an example of VFG setup using Bootstrap 3, without the VFG CSS, showing a two-column form with some two-column fields inside.

https://jsfiddle.net/zoul0813/k6gzcj6b/5/

**Comment by vesper8** [comment]
and what is the option for removing VFG's CSS since all we're doing is installing it via NPM and adding

```
import VueFormGenerator from "vue-form-generator";
Vue.use(VueFormGenerator);
```

**Comment by zoul0813** [comment]
@vesper8 you should have something like this

```
// the "full" way
<script>
  import VueFormGenerator from "vue-form-generator";
  import "vue-form-generator/dist/vfg.css";  // optional full css additions
</script>

// the "core" way
<script>
  import VueFormGenerator from "vue-form-generator/dist/vfg-core.js";
  import "vue-form-generator/dist/vfg-core.css";  // optional core css additions
</script>
```

You would just omit the '.css' import.
