### ISSUE TITLE
staticMap not showing up

### ISSUE THREAD

**Issue by zopyx** [vue-generators/vue-form-generator#385]
I have a fresh checkout as of today. I have modified main.js of examples/simple/main.js with this staticMap however the maps is being displayed.

```
		schema: {
			fields: [

                                {
                    type: "staticMap",
                    label: "Map",
                    model: "address.geo",
                    visible: false,
                    staticMapOptions: {
                        lat: "latitude",
                        lng: "longitude",
                        zoom: 6,
                        sizeX:640,
                        sizeY:640,
                        scale: 1,
                        format:"png",
                        // maptype:"satellite",
                        language:"FR-fr",
                        // region:
                        markers:"color:blue%7Clabel:S%7C43.107733,4.541936",
                        // path:
                        // visible:
                        // style:"feature:road.highway%7Celement:labels.text.stroke%7Cvisibility:on%7Ccolor:0xb06eba&style=feature:road.highway%7Celement:labels.text.fill%7Cvisibility:on%7Ccolor:0xffffff",
                        // key:
                        // signature:
                    }
                },

				{
					type: "input",
					inputType: "text",
					label: "ID",
					model: "id",
					readonly: true,
					featured: false,
					disabled: true
				},
			]

```

<img width="1086" alt="bildschirmfoto 2018-01-25 um 12 51 05" src="https://user-images.githubusercontent.com/594239/35387023-78334fa0-01ce-11e8-8fc9-65b8da2aa89d.png">

**Comment by zoul0813** [comment]
Did you update the reference in examples/simple/index.html and point it at vfg.js instead of vfg-core.js ? The simple example only includes `vfg-core.js` which does not provide access to the optional fields (fieldStaticMap.vue is an optional field and only provided in vfg.js)

**Comment by zoul0813** [comment]
It also looks like you have `visible: false` on the staticMap schema, which will prevent it from being displayed as well.

**Comment by zopyx** [comment]
ok, with vfg.js and `visible: true` I can see the label but still no map

Modified ``main.js``:

```
        data: {
                model: {
            lat: 40,
            lng: 30,
            address: "Dudweiler",
                },
                schema: {
                        fields: [

                    {
                    type: "staticMap",
                    label: "Map",
                    model: "address",
                    visible: true,
                    staticMapOptions: {
                        lat: "lat",
                        lng: "lng",
                        zoom: 6,
                        sizeX:640,
                        sizeY:640,
                        scale: 1,
                        format:"png",
                        language:"FR-fr"
                    }
                },

                        ]
                },

                formOptions: {
                        validateAfterLoad: true,
                        validateAfterChanged: true
                }
        }
```

**Comment by zoul0813** [comment]
Your model should look like this:

```
model: {
  address: {
    lat: 40,
    lng: 30,
  }
}
```

The staticMap component expects the lat/lng to be contained within an object in your model, so if you tell it to use `address` for the `model` then it expects to see `address.lat` and `address.lng` properties.

**Comment by zopyx** [comment]
Getting closer but this gives a 403 for 

staticmap:1 GET http://maps.googleapis.com/maps/api/staticmap?center=30,50&zoom=6&size=640x640&scale=1&format=png

**Comment by zoul0813** [comment]
That link works fine for me (centering around the Persian Gulf).

403 is an unauthorized error ... you'll need to refer to the google maps api documentation to resolve issues with their API.  

Looks like the VFG related issues you were having are now resolved.  Mind if I close this issue?

**Comment by zopyx** [comment]
Don't get me wrong but what should I check with the Google Maps API here? I know that you need an API key for certain operations. If an API key is need for using staticMap, so how can I configure it. Is there a working example for staticMap?

**Comment by zopyx** [comment]
It's the scale factor.

**Comment by zoul0813** [comment]
Unfortunately, I can't provide assistance with the Google Maps API as I haven't used it in quite some time.  The VFG Docs should provide the necessary links and information you need to get started though.

https://icebob.gitbooks.io/vueformgenerator/content/fields/staticmap.html

This refers to https://developers.google.com/maps/documentation/static-maps/intro and states that the "key" property for staticMapOptions is where you would place your key, you may also require the "signature" property depending on your Google Maps account setup.
