### ISSUE TITLE
Custom Template with Radiobuttons.

### ISSUE THREAD

**Issue by maximaexchen** [vue-generators/vue-form-generator#388]
I could not get it to work.
Made it like the example.
Radio imputs are visible in the main form.
But the are not recognized as a 
```
<template>
<div>
    <input value="plan1" checked="" type="radio" v-model="selectedplan"> One
    <input value="plan2" checked="" type="radio" v-model="selectedplan"> Two
    <input value="plan3" checked="" type="radio" v-model="selectedplan"> Threee
</div>
</template>
```
I can select all of them. v-model does not seem to catch.

Any Advice.

**Comment by zoul0813** [comment]
Can you provide a JSFiddle example?

**Comment by maximaexchen** [comment]
Sorry my html was not shown correctly.
I would provide a fiddle but, to be honest, I have no clue how to do that.
I will try to figure it out.

**Comment by zoul0813** [comment]
Not sure what your attempting to do here with custom templates.  What you've provided above does not appear to be VFG related.  If it's a custom field component for VFG, can you provide all of the component code as well?

**Comment by maximaexchen** [comment]
What I try to achive is a more complex output of three radio-selects which need complex html.
See screenshot.
I could be true, that I am totaly wrong herer.

![bildschirmfoto 2018-01-31 um 20 06 39](https://user-images.githubusercontent.com/9976576/35642099-561178cc-06c2-11e8-8e56-2775017f6c15.png)

**Comment by maximaexchen** [comment]
I think I found my problem.
I had to add 
```
props:["selectedplan"]
```
into the component.  Now everything works fine.
Why does it work without "props" in other examples I found?

**Comment by zoul0813** [comment]
@maximaexchen I can't answer that question without seeing the code to your component.
