### ISSUE TITLE
Allow to select all options in a checklist input

### ISSUE THREAD

**Issue by raphaelarias** [vue-generators/vue-form-generator#391]
Hi.

Would it be possible to have "All options" option in the checklist input? So when the user selects it, VFG automatically selects all the options?

**Comment by zoul0813** [comment]
@raphaelarias you could use a submit button with a custom "onSubmit" handler that checks/unchecks everything ... but currently, the checklist component does not support that.

[Fiddle Example](https://jsfiddle.net/zoul0813/p57e5kb7/)

The better solution might be to use the existing fieldChecklist.vue in src/fields/core/ as a base, and create a custom field component from it adding this functionality.

**Comment by raphaelarias** [comment]
Would this something you would like to have a Pull Request to be merged in the core codebase?

**Comment by zoul0813** [comment]
It’s a possible addition to v3 - sure. 

I would think that this would fall under the optional components though, as it would require quite a bit of configuration and schema options to make a “check all” feature work for “everyone” (from a styling point of view)

**Comment by raphaelarias** [comment]
Ok, we will work on something here and we create a Pull Request.

**Comment by zoul0813** [comment]
@raphaelarias I'm going to close this issue, but before I do I wanted to provide an additional option using the field schemas ["buttons" parameter](https://icebob.gitbooks.io/vueformgenerator/content/fields/inside_buttons.html).  This is similar to the above mentioned submit buttons solution, but takes advantage of the built-in "inside buttons" available to all fields.

[JSFiddle Example](https://jsfiddle.net/h0nxcnpc/)

```
{
  type: "checklist",
  label: "CHECKLIST combobox",
  model: "checklistcombobox",
  buttons: [
      {
      label: "Check All",
      classes: "btn btn-sm btn-link",
      onclick: (model, field, event, $this) => {
        console.log(model, field, event, $this);
        this.model.checklistcombobox = checklistOptions.map((o) => { 
          return o.value 
        });
      }
    },
    {
      label: "Uncheck All",
      classes: "btn btn-sm btn-link",
      onclick: (model, field, event, $this) => {
          this.model.checklistcombobox = [];
      }
    }
  ],
  listBox: false,
  values: checklistOptions
}
```
