### ISSUE TITLE
How to declare custom validator?

### ISSUE THREAD

**Issue by rivmar** [vue-generators/vue-form-generator#395]
I tried this:
```
schema: {
          {
            type: 'input',
            inputType: 'number',
            validator: [VueFormGenerator.validators.number, 'checkAmount'],
            ...
},
...
methods: {
    checkAmount(value) {
      return ["Validation performed!"];
      }
```
but seems checkAmount is newer called.
How to declare custom validator in schema?
Thank you in advance.

**Comment by zoul0813** [comment]
Custom validators have to be function references, strings always point to internal VFG validators.

**Comment by dflock** [comment]
The docs for this are here: https://icebob.gitbooks.io/vueformgenerator/content/validation/

But the docs aren't explicit enough about this. They do tell you that if you use a string, it's a shortcut for a built-in `validator.<string>` function - and that you can just use any function that's in scope - but doesn't give an example for doing this.

To make you example work, just remove the quotes:

```js
schema: {
          {
            type: 'input',
            inputType: 'number',
            validator: [VueFormGenerator.validators.number, checkAmount],
            ...
},
...
methods: {
    checkAmount(value) {
      return ["Validation performed!"];
      }
```

**Comment by zoul0813** [comment]
I'd also like to point out that you can hijack the `VueFormGenerator.validators` object and either replace it, or modify it ... which is useful when your schema's are being retrieved from a remote API and can't contain references to functions.

Something like this:

```
VueFormGenerator.validators.customValidatorFn = function(value) {
  if(false) {
    return ['Invalid'];
  else {
    return [];
  }
}
```

You can then reference this new validator using the string `"customValidatorFn"`, I'd recommend prefixing all of your custom functions to keep them together.
