### ISSUE TITLE
How do you use the new upload field?

### ISSUE THREAD

**Issue by fwarren** [vue-generators/vue-form-generator#400]
Some documentation or an example would be helpful.

**Comment by zoul0813** [comment]
The upload field needs documentation.

Here's a quick example of use, based on the fields/core/fieldUpload.vue code ... it appears to support the following schema options:

```
inputName,
onChange,
accept,
multiple,
placeholder,
readonly,
required,
disabled
```

Here's an example schema
```
{
  type: 'upload',
  inputName: 'the-name-attribute-on-the-input-field',
  onChange: (model, schema, event, instance) {
    // do some stuff with the information provided, such as upload the file
  }
}
```

**Comment by fwarren** [comment]
This is still not enough info.
```
{
  type: 'upload',
  inputName: 'the-name-attribute-on-the-input-field',
  onChange: (model, schema, event, instance) {
    // do some stuff with the information provided, such as upload the file
  }
}
```
no idea what inputName should be, and no idea in model, schema, event, or instance I would find the file information. And would I really want to upload a file at the onChange point?

**Comment by zoul0813** [comment]
`inputName` is the value you want the `<input type="file" name="inputName" />`

model, schema, event, and instance are the arguments passed to the onChange handler ... model is the name of the model property, and schema is the schema object that defines the field.  event is the "change" event that was fired, and instance is a reference to the fieldUpload component itself.

**Comment by morris821028** [comment]
The latest version, please use "onChanged", not "onChange".

https://github.com/vue-generators/vue-form-generator/blob/bc44da9e7c187800ac84a5632f698e5ea893871a/examples/post-form/main.js#L104
