### ISSUE TITLE
Getting warning: The 'file' type in input field is deprecated

### ISSUE THREAD

**Issue by jewbetcha** [vue-generators/vue-form-generator#402]
Thanks a bunch for this package :)

I'm getting this warning:
```
The 'file' type in input field is deprecated. Use 'file' field instead.
```
when using this kind of field:
```
{
    type: "input",
    inputType: "file"
}
```
I can't find anything in the documentation about what to do instead of this, even though it says I shouldn't use `type: "input"` for type `file`. I've tried just `type: "file"` but then I get an error about an unregistered custom file type.

What is the recommended alternative?

**Comment by zoul0813** [comment]
You need to use the 'upload' field, 

```
{
  type: 'upload',
  onChange: (model, schema, event, instance) { }
  ...
}
```

The upload field doesn't appear to be documented...

**Comment by jewbetcha** [comment]
Thank you! Correct, this field is not documented.

**Comment by zoul0813** [comment]
Related to #400 - additional usage and sample code can be found here.

https://github.com/vue-generators/vue-form-generator/issues/400
