### ISSUE TITLE
Custom label/field wrapper

### ISSUE THREAD

**Issue by outOFFspace** [vue-generators/vue-form-generator#403]
How to build such template

```
<div class="rows">
<div class="label">Regions</div> 
<div class="indent">
<select name="region" id="region" class="boxed elem mb-15">
<option value="">Select region</option>
</select>
</div>
</div>
```

**Comment by zoul0813** [comment]
VFG doesn't support passing custom templates ... but if you require custom markup, you can always [create your own VFG field components](https://icebob.gitbooks.io/vueformgenerator/content/fields/custom_fields.html).

You can however assign custom CSS classes to certain DOM elements created by VFG.  For example `styleClasses`, `fieldClasses`, `labelClasses` and `tag`.

You can pass `tag` directly into `<vue-form-generator tag="div" />`, and `styleClasses`  and `labelClasses` are passed into the various field schemas ...

```
{
  type: "select",
  styleClasses: "rows",
  labelClasses: "label",
  fieldClasses: "boxed elem mb-15"
}
```

This will produce a markup "similar" to what you have ... but won't be exact.

**Comment by gentunian** [comment]
@zoul0813 it seems that this doc is outdated: https://icebob.gitbooks.io/vueformgenerator/fields/field_properties.html

Nothing mention `fieldClasses` and `labelClasses` there :(

**Comment by gentunian** [comment]
I would love to help. Not sure how, as I can't find where the docs for gitbook are. I think it should be added to gitbook instead of README.md.
