### ISSUE TITLE
Add VFG to CDN services

### ISSUE THREAD

**Issue by networkimprov** [vue-generators/vue-form-generator#405]
Allowing installation of VFG like this
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.13/vue.min.js"></script>
```

**Comment by zoul0813** [comment]
@networkimprov The CloudFlare CDN you provided as an example has a "request library" feature which you are welcome to submit a ticket to.

Here's a link to the Issue Request provided by CloudFlare.  This is a simple GitHub Issue request filed with cdnjs's github repo requesting them to add a library of your choice to their repository.  We have no direct control over this.

[Request VFG Be Added to CloudFlare](https://github.com/cdnjs/cdnjs/issues/new?title=%5BRequest%5D%20Add%20vue-form-generator&body=**Library%20name%3A**%20vue-form-generator%0A**Library%20description%3A**%20%0A**Git%20repository%20url%3A**%20%0A**npm%20package%20name%20or%20url**%20%28if%20there%20is%20one%29%3A%20%0A**License%20%28List%20them%20all%20if%20it%27s%20multiple%29%3A**%20%0A**Official%20homepage%3A**%20%0A**Wanna%20say%20something%3F%20Leave%20message%20here%3A**%20%0A%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0ANotes%20from%20cdnjs%20maintainer%28please%20remove%20this%20section%20after%20you%20read%20it%29%3A%0A1.%20Please%20read%20the%20%5BREADME.md%5D%28https%3A//github.com/cdnjs/cdnjs%23cdnjs-library-repository%29%20and%20%5BCONTRIBUTING.md%5D%28https%3A//github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md%29%20document%20first.%0A2.%20For%20the%20new%20library%20request%20issue%2C%20please%20make%20sure%20it%27s%20not%20a%20personal%20project%2C%20we%20have%20a%20basic%20requirement%20for%20the%20popularity%2C%20like%20200%20stars%20on%20GitHub%20or%20800%20downloads/month%20on%20npm%20registry.%0A%0AWe%20encourage%20you%20to%20add%20a%20library%20via%20sending%20pull%20request%2C%0Ait%27ll%20be%20faster%20than%20just%20opening%20a%20request%20issue%2C%0Asince%20there%20are%20tons%20of%20issues%2C%20please%20wait%20with%20patience%2C%0Aand%20please%20don%27t%20forget%20to%20read%20the%20guidelines%20for%20contributing%2C%20thanks%21%21)

In addition, you can also use the [unpkg](https://unpkg.com/#/) CDN, which is used regularly for JSFiddle samples in the documentation and for issue support.

```
<!-- full vfg -->
<script src="https://unpkg.com/vue-form-generator@2.2.0/dist/vfg.js"></script>
<link rel="stylesheet" href="https://unpkg.com/vue-form-generator@2.2.0/dist/vfg.css" />

<!-- vfg-core only -->
<script src="https://unpkg.com/vue-form-generator@2.2.0/dist/vfg-core.js"></script>
<link rel="stylesheet" href="https://unpkg.com/vue-form-generator@2.2.0/dist/vfg-core.css" />
```

**Comment by networkimprov** [comment]
Maybe include the above code for unpkg in the installation docs? Most other JS libs I've seen do this...
