### ISSUE TITLE
How to bind values with Vuex

### ISSUE THREAD

**Issue by onhernandes** [vue-generators/vue-form-generator#407]
How could I bind model values with Vuex?

**Comment by zoul0813** [comment]
You could use the `v-on:model-updated` event in VFG to dispatch/commit your data changes as they occur, if you need that functionality.  

Alternatively, you could also use the `v-on:validated` event, which is triggered every time the form validates data (this way you can just `this.$store.commit('model', this.model)` in the onValidated() handler).  This would allow you to selectively commit your model based on whether or not it is valid.

Here's an example ...
template:
```
<vue-form-generator ... @validated="onValidated" @model-updated="onModelUpdated"></vue-form-generator>
```

component:
```
onModelUpdated(model, schema) {
  this.$store.dispatch('update', {
    model: model,
    schema: schema
  });
},
onValidated(isValid, errors) {
  if(isValid) {
    this.$store.commit('model', this.model);
  } else {
    // decide what to do with invalid models here
  }
}
```

store:
```
const store = new Vuex.Store({
  ...,
  mutations: {
    model: (state, payload) {
      Vue.set(state, 'model', payload);
    }
  }
  actions: {
    update(context, payload) {
      // clone the existing model
      let model = Object.assign({}, context.state.model);
      model[payload.schema] = payload.model;
      context.commit('model', model);
    }
  }
}
```

**Comment by onhernandes** [comment]
Great! And what about listening data from Vuex? The only way I achieved this was by creating a computed property for listening any property and updating everything in the model, also, needed to put something like `:useless="computed_property"`. It's dirty, but its working.
Thanks!

**Comment by zoul0813** [comment]
What are you trying to accomplish exactly?

**Comment by onhernandes** [comment]
Right on mounted, load user data from Vuex, then after editing and submitting, the data will be sent back do Vuex through an action, then sent to an endpoint and finally, updating the Vuex state itself or showing an error. For loading the first state from Vuex, I did like said in the last comment(using a computed property for loading data from Vuex)

I really don't know if that's the best approach, but it works(and I'm learning haha)

**Comment by zoul0813** [comment]
You can use the `submit` feld with an `onSubmit` handler to handle everything after the "editing and submitting" part of your workflow ... the `onSubmit` handler will be notified when the user clicks the "Save/Submit/Update" button in your form, and you can then write the form model into VueX's store by dispatching it to an action ... the action can then be responsible for committing the update into the store and making your remote endpoint call.

**Comment by onhernandes** [comment]
Ok, thank you!
