### ISSUE TITLE
Check for existence of fields?

### ISSUE THREAD

**Issue by zopyx** [vue-generators/vue-form-generator#412]
plone.restapi performs a good validation (or the field validation does it). However plone.restapi does not check for the existence of a field. So you can send `'foo': 'bar'` as part of patch request. Perhaps it would make sense to check if field `foo` really exists and report this as an error?

**Comment by zoul0813** [comment]
If the field is marked as required then VFG will not validate the form unless it has a valid value.

phone.restapi appears to be a python package - unrelated to VFG?

**Comment by zopyx** [comment]
Sorry, complete different bugtracker :)
