### ISSUE TITLE
Insufficient error reporting, more humane validation/error messages needed

### ISSUE THREAD

**Issue by zopyx** [vue-generators/vue-form-generator#413]
I have a Dexterity content type with a `table`  z3cform.datagridfield with a row specification that contains

```
class ITableRowSchema(form.Schema):

    date_from = schema.Date(
        title=_(u'Start date'),
        required=True,
        defaultFactory=default_date
    )
   ...
```

If you pass an ISO8601 string for `date_from`  then the error is:
```
  Module plone.restapi.deserializer.dxcontent, line 114, in __call__
BadRequest: [{'field': 'table', 'message': u'Wrong contained type', 'error': WrongContainedType([WrongContainedType([AttributeNotFoundError(), AttributeNotFoundError(), AttributeNotFoundError()], '')], 'table')}]
```

The error message does not contain the name of the offending field `date_from` but three times it mentions `AttributeNotFoundError()`.

If you omit the require field `date_from` then the error is also bit useless:

```
BadRequest: [{'field': 'table', 'message': u'Wrong contained type', 'error': WrongContainedType([WrongContainedType([AttributeNotFoundError(), 
AttributeNotFoundError(), AttributeNotFoundError(), AttributeNotFoundError()], '')], 'table')}]
```

As a user of the REST api I am interested in more precise error message instead of propagating back "internal" tracebacks/errors.

**Comment by zoul0813** [comment]
Wrong project?

**Comment by zopyx** [comment]
Sorry, yes, wrong tracker
