### ISSUE TITLE
Programtically change selected option

### ISSUE THREAD

**Issue by fwarren** [vue-generators/vue-form-generator#416]
Is there some way to change the currently selected option? An example would be if a zipcode is entered into a text box and we now know the state, could we automatically change the selected state option?

**Comment by zoul0813** [comment]
You can bind to the model changed event on the VFG instance, and then run any logic you wish... if you update the model bound to VFG it will reflect the change.  I can provide a sample of this later today or tomorrow if necessary.

**Comment by fwarren** [comment]
Yes some sample code would be great.

**Comment by zoul0813** [comment]
Here's a [JSFiddle](https://jsfiddle.net/zoul0813/x3a5oxm7/) showing how you can use the @model-updated event to evaluate and react to model changes.

In this example, if you change the postalCode value to "456789" the checklistcombobox will be updated to reflect two specific options, chosen in the onModelUpdated method ... it is probably best to check if the model you are modifying already has a value, and determine the best action to take in that event (ie; changing a user entered value in response to another user entered value).

Here's the main code ... 

```
<vue-form-generator :schema="schema" :model="model" :options="formOptions" @model-updated="onModelUpdated"></vue-form-generator>
```

```
onModelUpdated(newVal, schema) {
  // newVal is the value, and schema is the path for the property on the model
  console.log(newVal, schema);
  if(schema == 'postalCode' && newVal == '456789') {
    this.model.checklistcombobox = ['CSS3-123', 'CoffeeScript-123'];
  }
}
```

**Comment by fwarren** [comment]
Thank you so very much. I did not realize the ```<select>``` component is reactive and all I had to do was change ```this.model.mySelect``` to change the selection.

**Comment by zoul0813** [comment]
@fwarren everything should be reactive - if you come across anything that is not, do let us know by creating an issue.
