### ISSUE TITLE
Dealing with errors in file upload

### ISSUE THREAD

**Issue by fwarren** [vue-generators/vue-form-generator#417]
As near as I can tell there is no way to use a validator with the file upload. I can check to make sure no more than 5 files are being selected  with the code below
```
onChanged: function (event) {
  if (event.target.files.length > 5) {
    // do something here 
  }
}
```
I do not seem to have access to my components ```this``` So I am not sure what I can do here. I can't set any data properties nor call any methods on my component.

**Comment by fwarren** [comment]
I figured it out on my own, need to use ```this.$parent.$parent``` to access my vue page. 
```
onChanged: function (event) {
  if (event.target.files.length > 5) {
    this.$parent.$parent.alertText = 'Max of 5 files allowed'
  }
}
```

**Comment by zoul0813** [comment]
You can use this.$root to access the top most Vue instance (usually the "app" or "page" instance).  I'd recommend, however, using an Event Bus or State Management to notify components.
