### ISSUE TITLE
New field type : source code

### ISSUE THREAD

**Issue by gwenaelp** [vue-generators/vue-form-generator#419]
To allow people type source code in a better way in the forms, I have made a custom field, and I would like to register it to the list of available custom fields.

### Preview
![preview](https://user-images.githubusercontent.com/5365267/37572148-35904f4c-2b07-11e8-8883-40fd3dc6db63.png)

### Links

Repo : https://github.com/gwenaelp/vfg-field-sourcecode
NPM : https://www.npmjs.com/package/vfg-field-sourcecode

At the moment, it highlights all files as ".vue" files. I'm looking for ideas to be able to load the good syntax according to what has been set up in the schemas (have that kind of line, but dynamic : https://github.com/gwenaelp/vfg-field-sourcecode/blob/master/src/components/field-sourcecode.vue#L8). I'm still looking for ideas for that, so if you have one, let me know!

More custom fields to come! =D

**Comment by lionel-bijaoui** [comment]
Thanks a lot ! You are the first custom field (as far as I know).
We are in the process of updating to the v3 so be aware some changes might be needed.

**Comment by zoul0813** [comment]
Looks good.

I added the documentation tag to this issue, your field should be added to the README under the "Public Custom Fields" section.
