### ISSUE TITLE
fieldUpload `onChange` event throws ReferenceError in Firefox

### ISSUE THREAD

**Issue by jewbetcha** [vue-generators/vue-form-generator#422]
* **I'm submitting a ...**
  * [x] bug report

- **Do you want to request a _feature_ or report a _bug_?**
Bug
* **What is the current behavior?**
In Firefox latest (59.0.1), `fieldUpload` event `onChange` throws error `ReferenceError: event is not defined`. This issue does not exist in latest Chrome. Could it be related to the fact that Firefox does not support a global `window.event` object?

* **What is the expected behavior?**
The ability to access the event object for `fieldUpload` fields in the schema. ex:
```
onChanged: function(model, schema, event, instance) {
    const file = event.target.files[0];
}
```

- **What is the motivation / use case for changing the behavior?**
Need the ability to read/process file data on input upload.

* **Please tell us about your environment:**

  * Version: 2.2.1
  * Browser: Firefox 59.0.1
  * Language: ES6/7

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
It seems as though Firefox handles the event object a bit differently:
https://stackoverflow.com/questions/7457260/event-target-not-working-on-firefox
https://stackoverflow.com/questions/9636400/event-equivalent-in-firefox

**Comment by ik9999** [comment]
https://github.com/vue-generators/vue-form-generator/pull/438
Fix for the issue
