### ISSUE TITLE
New field type : array

### ISSUE THREAD

**Issue by gwenaelp** [vue-generators/vue-form-generator#424]
To allow people handle arrays in a better way in the forms, I have made a custom field, and I would like to register it to the list of available custom fields.

### Simple array 
![preview-simple](https://user-images.githubusercontent.com/5365267/37695875-da6a8e0c-2cd2-11e8-8814-8bfeca527b48.png)

### With a container component and with objects (and object custom field) as items
![preview-container-object](https://user-images.githubusercontent.com/5365267/37695905-19c763b8-2cd3-11e8-81c8-b88e81c87db0.png)

## Links
Repo : https://github.com/gwenaelp/vfg-field-array
NPM : https://www.npmjs.com/package/vfg-field-array

I think I am good for now, I need to improve tests and docs on the 3 components I released recently :smile:

**Comment by zoul0813** [comment]
Please submit a PR with an update to the README.md that adds this new component to the list of `Public Custom Fields`.

Thanks.
