### ISSUE TITLE
v2.2.0 doesn't validate properly

### ISSUE THREAD

**Issue by jaywilburn** [vue-generators/vue-form-generator#428]
I'm submitting a bug for the latest version of VFG

The latest version (2.2.0) will allow you to submit a form without allowing validation to work as it should. 

We are using VFG and want to make sure the user can't bypass any questions and submit a blank form.

Here's a fiddle:
https://jsfiddle.net/0mg1v81e/2105/

2.1.1 works, but 2.1.1 didn't have the $event param which we need to protect from post backs (putting this within a .NET app) without any issues so we upgraded to 2.2.0, only to find the form isn't handling validation right. If there is a workaround for this please let me know how I can hack this and release this app.

**Comment by zoul0813** [comment]
You should update to 2.2.1 (the latest), and implementing "onValidationError" solves the problem.

If you don't implement the "onValidationError" callback, then "onSubmit" can check the VFG instance's "errors" array to see if it is empty, and decide whether or not to proceed.

[Updated JSFiddle](https://jsfiddle.net/zoul0813/0mg1v81e/2113/)

**Comment by zoul0813** [comment]
You can use onValidation error to catch errors, or you can check the VFG instances errors array to see if any exist

Some of these changes haven’t made it into the docs yet
