### ISSUE TITLE
Can't set validationErrorClass without validationSuccessClass

### ISSUE THREAD

**Issue by afourmeaux** [vue-generators/vue-form-generator#429]
Hi,

### Currently :
In the form options, setting `validationErrorClass` to another class is ineffective unless you also set `validationSuccessClass` and the other way arroud.

### Expected :
Setting `validationErrorClass` or `validationSuccessClass` should work without setting the other.

**Comment by zoul0813** [comment]
PR #446 closes this.  If the PR does not get merged, you can reopen this issue - thanks.
