### ISSUE TITLE
hideNoneSelectedText and noneSelectedText not working

### ISSUE THREAD

**Issue by alessandrotesoro** [vue-generators/vue-form-generator#432]
* **I'm submitting a ...**
  * [x] bug report

- **Do you want to request a _feature_ or report a _bug_?**
It's a bug.

* **What is the current behavior?**
Nothing happens.

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
The field shouldn't have the "none selected" option or "jjj" (random text) should appear but none of the options work.
https://www.dropbox.com/s/87jr5e7tyhv76y0/Schermata%202018-04-04%20alle%2019.28.59.png?dl=0
https://www.dropbox.com/s/lr0gu99yc10veip/Schermata%202018-04-04%20alle%2019.29.10.png?dl=0

Also doesn't work on the demo https://jsfiddle.net/g77z8b8r/

* **What is the expected behavior?**
Should either hide the none selected option or should change it's name, but none of the options work.

Is this a bug or have I done something wrong?

**Comment by zoul0813** [comment]
The `noneSelectedTest` and `hideNoneSelectedText` properties belong inside of a `selectOptions` property.

[JSFiddle](https://jsfiddle.net/4j46c32c/)

**Comment by GajendraMehra** [comment]
In case it did not work use  the following values
                            
                             selectOptions: {
                                    noneSelectedText: 'test',
                                     hideNoneSelectedText: true,
                                },
                                
                                required: true,
                                values: function() {
                                return [
                                    { id: null, name: "-- Select -- " },
                                    { id: "0", name: "No" },
                                    { id: "1", name: "Yes" },
                                ]
                                },
                                default: null,
