### ISSUE TITLE
If a checklist or select is required it's not processed in the validation 

### ISSUE THREAD

**Issue by afourmeaux** [vue-generators/vue-form-generator#433]
### Current :
When a select or a checklist is required and if nothing is checked / selected, the `@validated` `isValid` value is `true` and no error message is displayed.

### Expected :
The `isValid` should be setted to `false` and `error` should contain the errors, and some error message should appear bellow saying that it's required.

**Comment by afourmeaux** [comment]
Nevermind i found a work arround...

So to have the required state checked :
* for the **checklist** you have to use 
````
min: 1,
validator: VueFormGenerator.validators.array,
````
* for the **select** you have to use 
````
min: 1,
validator: VueFormGenerator.validators.string,
````

**Comment by zoul0813** [comment]
The problem is that the `required` validator is a bit "simple", in that it only checks if the value being passed in `isNil` (null || undefined) or is an empty string.  An empty array is neither of these, and so passes the `required` validation.

We can probably make the `required` validator a bit more intelligent... where it can check to see if the value being passed in is an array, and if so, test it's length.

**Comment by metalsimyaci** [comment]
I could not run required for the select object.
I think that the problem is caused by not setting the default option.
I use it this:
`{type: "select",label: "theLabel", model: "theSelectId",
                                    selectOptions: {hideNoneSelectedText: true, value: "id",name: "name" },
                                    values: function() {
                                        return [ { id: 1, name: "A" }, { id: 2, name: "B" },{ id: 3, name: "C" },{ id: 4, name: "D" },{ id: 5, name: "E" }];
                                    },                                    
                                    required: true,
                                    validator: VueFormGenerator.validators.required,
                                    styleClasses: "col-md-6"
                                }`
Thanks for your help.
Thanks for library.
