### ISSUE TITLE
validateBeforeSubmit doesn't prevent the submit

### ISSUE THREAD

**Issue by afourmeaux** [vue-generators/vue-form-generator#434]
### Current : 
When an input submit has `validateBeforeSubmit` setted to `true` the form is not prevented from submitting and call the `onSubmit` callback when there is errors.

### Expected :
It should not submit if there is errors.

**Comment by zoul0813** [comment]
Please refer to #408 - I recommend not placing VFG inside of a form, if you do, that form should have it's own onSubmit handler.

I've pushed a change that calls `$event.preventDefault()` when using `validateBeforeSubmit: true`, which means that `onSubmit` and `onValidationErrors` will both require you to manually submit the form if you would, as we can't capture async validation and prevent the `submit` event on failure.

**Comment by ppusapati** [comment]
use @click.prevent="onSubmit" rather than @submit.
