### ISSUE TITLE
Bug: date input doesn't work on 2.2.0

### ISSUE THREAD

**Issue by Kize** [vue-generators/vue-form-generator#436]
Hi there,

I noticed a bug on the last release of your plugin.

On 2.1.1, the input `type='date'` works perfectly, it can be tested on [this fiddle](https://jsfiddle.net/0mg1v81e/2500/)

On 2.2.0, vue-form-generator uses a **valueAsDate** property of the input, which returns a timestamp instead of a string (YYYY-MM-DD), which breaks the input. (See the console warning after the onBlur event, it specifies that a timeStamp is given)

The bug can be reproduced on [this fiddle](https://jsfiddle.net/0mg1v81e/2501/). The input resets itself on blur. 

<hr>
It seems to come from #363, but I'm not sure of it...

**Comment by Kize** [comment]
@zoul0813 your solution is kind of a workaround, as you can't choose the format of your date.
You have to specify that `format: 'YYYY-MM-DD'` in order to make it work. (a HTML input date doesn't allow other format)

So there is still a major breaking change between 2.2.1 and 2.2.x, as an optional property becomes mandatory.

But anyway, thanks for your answer, it fixes my problem 😄

**Comment by zoul0813** [comment]
@Kize I wasn't aware of the HTML5 Date Fields requirement to be in YYYY-MM-DD format.  I'm flagging this as a bug, and will try to get the date field to default to the YYYY-MM-DD format so you don't have to specify it manually.

**Comment by zoul0813** [comment]
Fixed in #557
