### ISSUE TITLE
validation with onfocus out

### ISSUE THREAD

**Issue by vinke1996** [vue-generators/vue-form-generator#439]
Is there a way that de validator can validate with onfocusout or something?
So that if a person skips the input field with 'tab' it validates the input field?

**Comment by zoul0813** [comment]
You can use `validateAfterLoad` in the `options` to have VFG validate the model before the user enters any data.  The only time skipping a field would be invalid is if the field was required, and VFG displays a "required *" near the field to indicate this and most modern browsers do a pretty good job of letting the user know these are required fields as well.

You can also listen for the `tab` key and tell VFG to revalidate the model by calling `vfg.validate()`.  If I understand the docs for `onfocusout` you can bind this event to a container that holds VFG and the event should bubble up notifying you of any focusout events below it ... and you can then run `vfg.validate()` there as well.
