### ISSUE TITLE
Question:Vue form generator client. 

### ISSUE THREAD

**Issue by fatagun** [vue-generators/vue-form-generator#440]
I am looking for a client to generate Vue form schemas as follows;

Is there a visual client to generate this schema? Or a cli?

How can I make it easy to generate such schema?

`
schema: {
      fields: [{
        type: "input",
        inputType: "text",
        label: "ID (disabled text field)",
        model: "id",
        readonly: true,
        disabled: true
      },{
        type: "input",
        inputType: "text",
        label: "Name",
        model: "name",
        placeholder: "Your name",
        featured: true,
        required: true
      },{
        type: "input",
        inputType: "password",
        label: "Password",
        model: "password",
        min: 6,
        required: true,
        hint: "Minimum 6 characters",
        validator: VueFormGenerator.validators.string
      }`

**Comment by lionel-bijaoui** [comment]
You did not respected the issue template.
This is an issue tracker, not a Q&A forum.
I see you asked the same question [on stackoverflow](https://stackoverflow.com/questions/49908990/vue-form-generator-client) as you should have.
