### ISSUE TITLE
Feature: add ability to hide or show fields using + or  - button 

### ISSUE THREAD

**Issue by Anand-Moghe** [vue-generators/vue-form-generator#441]
* Version: [2.X.X | 3.0.0-beta.X]
  * Browser: all | Chrome XX | Firefox XX | IE XX | Safari XX  
  * Language:  TypeScript X.X | ES6/7 | ES5 

Is it possible to add a feature that will allow any model field to be hidden or visible ?
E.g when it generates the form, we can show the hidden fields in the header as a button and it will allow user to hide or show (kind of toggle the visibility) the fields on the form.

**Comment by zoul0813** [comment]
The UI for this would be fairly dependent on the project.  You can, however, create custom fields.

You might also look into adding a hide/show UI above the form and toggling the “type” of the field in the scheme between “hidden” and whatever it should be set too, the dchemanchange should be picked up dynamically and the form should rerender the display accordingly.

**Comment by zoul0813** [comment]
Here's an [example of the second idea](https://jsfiddle.net/0mg1v81e/2709/), note the 'toggle' function and how it's being used.
