### ISSUE TITLE
How to select multiple columns to put the field

### ISSUE THREAD

**Issue by mehdimb6** [vue-generators/vue-form-generator#442]
I searched a lot
But I did not find a way to adjust the multi-column
How to put multiple fields together?
There is really no way to do this

**Comment by zoul0813** [comment]
What are you trying to accomplish?

**Comment by zoul0813** [comment]
Please refer to #401, #403, and this [JSFiddle](https://jsfiddle.net/zoul0813/k6gzcj6b/5/)

**Comment by mehdimb6** [comment]
Thank
