### ISSUE TITLE
Field wrap component

### ISSUE THREAD

**Issue by mix359** [vue-generators/vue-form-generator#459]
* **I'm submitting a ...**
  * [ ] bug report
  * [x] feature request

I would like to ask if is possible to have an optional wrap component for a fields (or all the fields).
I need to create a strange form, where you have to enable/disable the field before using it.
I've started that by doing a custom field that would show a fake/disabled field with the value, and when you unlock it, it show the real field. But with this approach I have problem redeclaring and importing the original field.
Would be really useful if I can pass in the schema of the field, a wrapper component that is placed in the form and receive as the default slot the real field, and some other information (like the schema, model, etc) as props. 
In this way we can create wrapper that interact with the field, or simply create more complex view.

Thanks 
Best regards
Daniele

**Comment by zoul0813** [comment]
This feature is beyond the scope of VFG.  Your use case seems very particular to your application and doesn’t seem highly reusable.

My recommendation would be to just create a custom field component that is capable of receiving the real fields type, then adding that real field using a v-if ... look at the main VFG template for examples on how to add unknown fields (component tag with “is” attribute)
