### ISSUE TITLE
cleaver.js with vue-form-generator. "Unknown custom element: "

### ISSUE THREAD

**Issue by franklinvvidal** [vue-generators/vue-form-generator#463]
I use VueFormGenerator with cleaver.js, after adding the following code(according to the documentation) i get the error "Unknown custom element: ". cleaver.js has installed via npm. Field data below:
```
{
  type: "cleaver",
  inputType: "text",
  label: "Phone",
  model: "phone",
  required: true,
  placeholder: "Digite seu número de telefone",
  validator: VueFormGenerator.validators.string,
  cleaveOptions: {
   phone: true,
   phoneRegionCode: "pt-BR"
  }
 }
```
Thanks for help.

**Comment by zoul0813** [comment]
Change `type` to `cleave`, not `cleaver`.

**Comment by franklinvvidal** [comment]
Thanks, sorry for that...
