### ISSUE TITLE
Input type `button` onclick event is not working.

### ISSUE THREAD

**Issue by tim-yao** [vue-generators/vue-form-generator#464]
I'm submitting a bug report.

Bug demo:
https://jsfiddle.net/tyao/2acmshqe/
The input button `onclick` callback function is not work.

- **What is the expected behavior?**
The button `onclick` callback function should work.

- **What is the motivation / use case for changing the behavior?**
Need a button to reset the whole form.

* **Please tell us about your environment:**

  * Version: [2.2.3]
  * Browser: [Chrome XX ]
  * Language: [ ES6 ]

**Comment by zoul0813** [comment]
Button is not a supported input type, as it doesn’t map to a model property.

You can use the  field buttons, per documentation ( https://icebob.gitbooks.io/vueformgenerator/content/fields/inside_buttons.html ) to allow users to click buttons related to supported field types.

You may also want to look into custom fields if you need a button on your form.

https://icebob.gitbooks.io/vueformgenerator/content/fields/custom_fields.html
