### ISSUE TITLE
Localization for noneSelectedText

### ISSUE THREAD

**Issue by tursumbekov** [vue-generators/vue-form-generator#474]
* **I'm submitting a ...**
  * [x] feature request

- **Do you want to request a _feature_ or report a _bug_?**
Request a _feature_

* **What is the current behavior?**
Missing

* **What is the expected behavior?**
Need localization

- **What is the motivation / use case for changing the behavior?**
Now I have access to validators localization through:
`VueFormGenerator.validators.resources.invalidNumber
...`
Need something like this.
Is this possible?

* **Please tell us about your environment:**

  * Version: [2.2.2]
  * Browser: [all]
  * Language: [all]

**Comment by zoul0813** [comment]
Duplicates #352
