### ISSUE TITLE
Changing the visibility of a pikaday control breaks the control

### ISSUE THREAD

**Issue by tomaustin700** [vue-generators/vue-form-generator#479]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  * [x] bug report
 
* **What is the current behavior?**
If there is a pikaday control and the control has its visibility toggled via a switch the control stops working correctly.

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://jsfiddle.net/u2o0jLdc/

Toggle the switch on, click on the date control and see the calendar is opened and a date can be selected, toggle the switch off then on again, see that the pikaday control stops working and doesn't open.

* **What is the expected behavior?**
The pikaday control should work consistently

* **Please tell us about your environment:**

  * Version: [2.1.1]
  * Browser: [all ]
  * Language: [all ]

**Comment by tomaustin700** [comment]
This only seems to happen if pikaday options are set.

**Comment by zoul0813** [comment]
This appears to have been resolved with v2.3.3

@tomaustin700 can you confirm?

Here's a Fiddle - https://jsfiddle.net/zoul0813/rnkhcoL7/

You can use either formatted dates ('2018-12-25') or Date.now() numbers ... and toggle the field on or off, and it appears to read and write the date properly as well as correctly init/destroy the pikaday elements.
