### ISSUE TITLE
Not including 'format' option in schema for an 'inputType: date' fails v2.2.2

### ISSUE THREAD

**Issue by evild70** [vue-generators/vue-form-generator#480]
Not including the `format` option in the schema an input with the `inputType: date` will cause validation to fail. It will reset the input and put the UNIX timestamp into the model. It will then put the following warning in the Chrome console:

```The specified value "1286686800000" does not conform to the required format, "yyyy-MM-dd".```

This issue does not exist in `v2.1.1`.

Correct schema:
```javascript
{
    type: 'input',
    inputType: 'date',
    model: 'date',
    format: 'YYYY-MM-DD',
    validator: VueFormGenerator.validators.date
}
```

Example: https://jsfiddle.net/evild70/w3e0p2a6/ (see Chrome console for warning)

I couldn't find any mention of this in the documentation.

**Comment by tomdickie** [comment]
There's an issue I came across in Chrome recently where in value always has to be set in the format yyyy-mm-dd, regardless of how it's displayed on the screen and the submitted value will also always be in the same format.

https://developers.google.com/web/updates/2012/08/Quick-FAQs-on-input-type-date-in-Google-Chrome

**Comment by zoul0813** [comment]
@evild70 is this still an issue in the latest 2.3.x?
