### ISSUE TITLE
Can templates be customised to achieve a horizontal form

### ISSUE THREAD

**Issue by birdy247** [vue-generators/vue-form-generator#482]
I did some digging and saw a labelClasses option.  I have tried playing around with the styleClasses and labelClasses option but cannot replicate a bootstrap horizontal form.

https://getbootstrap.com/docs/4.0/components/forms/#horizontal-form

Is this possible or would we have to create our own fields for this?

Thanks

**Comment by zoul0813** [comment]
This is basically what I have setup for creating bootstrap style forms.

Place your fields into "groups", and each group has a `styleClasses` option.  This is where you can define it as a `row` or any number of `col-**-**` classes.

Each field is also wrapped by a `form-group` container, and the `styleClasses` on the field is added to this.

You do not need to use the `labelClasses` since bootstrap automatically styles labels within a `form-group`.

```
{
	"groups": [{
			"legend": "Group Title",
			"styleClasses": "col-md-12",
			"fields": [{
					"type": "input",
					"inputType": "text",
					"styleClasses": "col-md-6",
					"model": "first_name",
					"label": "First Name"
				},
				{
					"type": "input",
					"inputType": "text",
					"styleClasses": "col-md-6",
					"model": "last_name",
					"label": "Last Name"
				}
			]
		},
		{
			"legend": "Email",
			"styleClasses": "col-md-6",
			"fields": [{
					"type": "input",
					"inputType": "text",
					"styleClasses": "col-md-6",
					"model": "email",
					"label": "Email"
				},
				{
					"type": "input",
					"inputType": "text",
					"styleClasses": "col-md-6",
					"model": "email_confirm",
					"label": "Email (Confirm)"
				}
			]
		},
		{
			"legend": "Password",
			"styleClasses": "col-md-6",
			"fields": [{
					"type": "input",
					"inputType": "text",
					"styleClasses": "col-md-6",
					"model": "password",
					"label": "Password"
				},
				{
					"type": "input",
					"inputType": "text",
					"styleClasses": "col-md-6",
					"model": "password_confirm",
					"label": "Password (Confirm)"
				}
			]
		}
	]
}
```

**Comment by zoul0813** [comment]
Here's a JSFiddle of this in action ... you'll want to expand the Fiddle preview section to show the multi-column layout.

https://jsfiddle.net/e740tao2/

**Comment by eventrac** [comment]
@zoul0813 Thanks for this.  I have managed to get it close to what we need, but not quite there: https://jsfiddle.net/e740tao2/15/  We are looking to get the label on the same line as the input.  We dont put fields side by side so I imagine every field would need to be its own group?

If we did want more control, how would you recommend?

Thanks

**Comment by zoul0813** [comment]
@eventrac that's a bit out of scope, and VFG doesn't have direct support for it (yet).

What I would do is create custom CSS classes for the core VFG CSS Classes (.form-group, .field-wrap, .wrapper, etc) and have them setup to inherit values from the bootstrap 4 styles.

**Comment by Patru85** [comment]
In case someone is still searching for a solution for this, I did the following:
My form is on a modal so it's not visible when the page loads. I've added a specific attribute to the field I wanted to be horizontal:
```
 {
    type: 'input',
    inputType: 'text',
    label: 'Your Field',
    model: 'yourfield',
    styleClasses: ["horizontal"]
 },
```
Than I start a function from the mounted cycle:
```
mounted() {
     this.handleHorizontal();
},
```
And the function looks like this with jQuery:
```
handleHorizontal() {
                $(".form-group").each(function() {
                    if ($(this).hasClass("horizontal")) {
                        $(this)
                            .find("label")
                            .css("width", "49.3%");
                        $(this)
                            .find(".field-wrap")
                            .css("width", "50%")
                            .css("display", "inline-block");
                    }
                });
            },
```
Adjust this to your needs and it's done, I hope it helps to someone :)
