### ISSUE TITLE
does not work with vue cli v3

### ISSUE THREAD

**Issue by nigel-dewar** [vue-generators/vue-form-generator#483]
Hi There, Im new to vue so likely the error is at my end.

You are likely already aware of this but just mentioning in case there was some easy fix

I tried installing vue-form-generator in a new vue cli c3 project but to no avail.

It doesnt work and console complains of weird issues where it cant access 'vue' and vue.use doesnt work.
![image](https://user-images.githubusercontent.com/9402456/44641809-43493200-aa0c-11e8-80bf-de73c276e190.png)

Kind Regards

Nigel Dewar

**Comment by genu** [comment]
Works fine for me, can you post some code?

**Comment by zoul0813** [comment]
Can you provide sample code and steps to reproduce?

**Comment by ChadTaljaardt** [comment]
Works for me and im running Vue cli3

**Comment by zoul0813** [comment]
closing - @nigel-dewar if you can provide some sample code that reproduces this issue, please feel free to reopen the issue.
