### ISSUE TITLE
How can I use it with Element-ui?

### ISSUE THREAD

**Issue by frinder6** [vue-generators/vue-form-generator#488]
* **I'm submitting a ...**
  * [ ] feature request

- **How can I use it with Element-ui, instead of original h5 element? thanks!**

**Comment by zoul0813** [comment]
there is no current or planned support for Element-UI.  VFG is a standalone library that attempts to separate itself from any larger dependencies.

With that said, you are welcome to fork the project and create an Element-UI spinoff of it.  If you do, please let us know and we'd be more than happy to link to it.
