### ISSUE TITLE
Add possibility to pass html attributes to the main HTML element of VueFormGenerator

### ISSUE THREAD

**Issue by guzun** [vue-generators/vue-form-generator#492]
Hi there.

I'm submitting a feature request

Currently, for the component properties, it is possible to specify the 'tag' (the default tag is 'fieldset'), but no attributes can be passed to it.

It would be nice to have the possibility to add custom attributes to the main HTML element of VueFormGenerator to make it easier to integrate with other components.

A good example of usefulness for such an option is integration with Vue.Draggable component https://github.com/SortableJS/Vue.Draggable
Integrating with that component requires using 'draggable' as the 'tag' and also pass the 'v-model' directive, which is currently not possible.

Or if there is another way to achieve such integration, please let me know.

Using version 2.2.2

Thank you,
Alex

**Comment by zoul0813** [comment]
Not sure if this answers your question entirely, but 2.2.2 supports an undocumented schema property called "attributes".

You can pass any additional HTML attributes you'd like to this.  By default, all attributes are attached to the "input" element in the field component, but there is also support for passing attributes to various other elements as well (support for each depends on the field component).

For example:

```javascript
{
  "type": "input",
  "inputType": "text",
  "model": "email",
  "attributes": {
    "data-toggle": "tooltip",
    "title": "some title text"
  }
}
```

Would create an `<input type="text" data-toggle="tooltip" title="some title text" />` element.

You can also do:

```javascript
{
  "type": "input",
  "inputType": "text",
  "model": "email",
  "attributes": {
    "wrapper": {
      "data-toggle": "collapse"
    },
    "input": {
      "special-input-attr": "special-value"
    }
  }
}
```

This would create the input field and add `data-toggle="collapse"` to the 'wrapper' element (`<div class="wrapper" data-toggle="collapse">`), and the `special-input-attr` would be added to the `<input />` element.

Have a look at the various components in src/fields/ and look for `"v-attributes="'location'"`, this will identify which elements can be targeted specifically.  All elements -should- support the 'input' target, and if you don't specify a target will default to he 'input' target.

As for adding attributes to the main element for VFG, you can just do:

```html
<vue-form-generator tag="draggable" :model="model" :schema="schema" custom-attribute="custom-value" seconnd-custom-attribute="second-custom-value"></vue-form-generator>
```

Whenever you add additional attributes that are not specified as "props" on a Vue component, they are automatically attached to or merged into the main element of the component.

I assume, however, that you'd like to use Vue.Draggable within VFG for sorting values in an array ... ? If so, VFG supports custom fields, and this is how you would implement the feature.  You can take a look at one of the community custom fields ([vfg-field-array](https://github.com/gwenaelp/vfg-field-array)) for an example of working with arrays ... and possibly even fork this and make it Vue.Draggable enabled.

**Comment by guzun** [comment]
@zoul0813, thanks  for the advice. 
I'll have to build custom fields to sort the values in the array.

Cheers!
