### ISSUE TITLE
Manually updating range slider attribute does not alter slider

### ISSUE THREAD

**Issue by OhligerJ** [vue-generators/vue-form-generator#496]
Feature Request/Bug Report

I am currently setting up a multi-step form where the input from one slider needs to effect the max of another. I can manually update the max using this.tabSchema.(tab-id).fields[0].rangeSliderOptions.max, but this doesn't change the UX at all. I can see in the console that max has been correctly updated, but the UX shows the old max.

Digging into the ion.RangeSlider documentation, I see that it has .update, .destroy, and .reset methods. However, these seem to require a function particular to jquery, .data(), in order to properly setup the slider object that you then call .update() upon. I do not see any documentation around this for use in Vue. Is there a known way to do this? If not, can this be implemented and documented?

**Comment by lionel-bijaoui** [comment]
Please use the correct issue template
