### ISSUE TITLE
Masking Library Not Loading/Functioning

### ISSUE THREAD

**Issue by OhligerJ** [vue-generators/vue-form-generator#499]
When trying to use the functionality outlined here: https://icebob.gitbooks.io/vueformgenerator/content/fields/masked.html, I get a JS error:
    JQuery MaskedInput library is missing. Please download from https://github.com/digitalBush/jquery.maskedinput and load the script in the HTML head section!

I tried including it a couple different ways, including doing exactly what it asked, but I kept receiving this error, and the masking didn't occur.

**Comment by zoul0813** [comment]
Did you include both jQuery and Masked Input? Load them in the head before VFG?

**Comment by OhligerJ** [comment]
jQuery isn't loaded in the head, but is loaded before VFG (rangeSlider works, for example). I loaded masked input in the head. Is there a way I need to include it for it to work with VFG?

**Comment by zoul0813** [comment]
You need to include it in the same fashion as jQuery, so it works with jQuery.  Add it after jQuery and before VFG.

**Comment by OhligerJ** [comment]
Good news: that worked. Thank you.

Bad news: we're now running into the issue brought up here: https://github.com/vue-generators/vue-form-generator/issues/335.  Has this been addressed in some way?

**Comment by OhligerJ** [comment]
Cheers. We did end up using cleave. For the sake of those using Cleave, the
phone masking is simply spaces for US, so if you want something like (000)
000-000, and don't want prefix to auto start you with an opening parens,
you need to use:
delimiters: ["(", ") ", "-"],
counts (I might be wrong about this key name): [0,3,3,4].
ᐧ
