### ISSUE TITLE
Validators are not working with v2.3.1

### ISSUE THREAD

**Issue by altunyurt** [vue-generators/vue-form-generator#508]
* **I'm submitting a ...**
  * [x ] bug report

- **Do you want to request a _feature_ or report a _bug_?**
Bug 

* **What is the current behavior?**
Validators are not working. 

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://jsfiddle.net/ or similar (you can use this template as a starting point: https://jsfiddle.net/icebob/0mg1v81e/).

https://jsfiddle.net/cLkse53u/1/ is the direct fork of official example, running on v2.3.1

* **What is the expected behavior?**

Validators should be working as they are in the example. 

* **Please tell us about your environment:**

  * Version:   2.3.1
  * Browser:  Chrome 67b, firefox 63b

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

No apparent reason or error logs

**Comment by zoul0813** [comment]
Related to #508

**Comment by altunyurt** [comment]
@zoul0813 this is #508

**Comment by zoul0813** [comment]
Related to #506
