### ISSUE TITLE
soft delete field

### ISSUE THREAD

**Issue by vahidalvandi** [vue-generators/vue-form-generator#514]
hi , i have idea for soft delete field , i added a new key by name `deleted : false` i need stay schema but not display in form !! also in select option value ?? 

* **I'm submitting a ...**
  * [ ] bug report
  * [x] feature request
  * [ ] support request => Please do not submit support request here, see note at the top of this template.

- **Do you want to request a _feature_ or report a _bug_?**

* **What is the current behavior?**

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://jsfiddle.net/ or similar (you can use this template as a starting point: https://jsfiddle.net/icebob/0mg1v81e/).

* **What is the expected behavior?**

- **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  * Version: [2.X.X | 3.0.0-beta.X]
  * Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  * Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by lionel-bijaoui** [comment]
Hi @vahidalvandi !
I'm really sorry, but don't understand.
If you have an idea that you think can improve VFG, please do a PR.

**Comment by vahidalvandi** [comment]
becuse delete a field remove stored data , if have feature for set deleted:true in field dont change old schema but hidden it
