### ISSUE TITLE
Can I get the V3 simple demo?

### ISSUE THREAD

**Issue by AruXc** [vue-generators/vue-form-generator#515]
I need more powerful groups and I saw the V3 have better groups #484 
but I don't understand how to use.

**Comment by lionel-bijaoui** [comment]
Check this : https://github.com/vue-generators/vue-form-generator-demo
clone it then do `npm install`, `npm run serve` and open the link.
Then, choose either "custom" or "group".
You will find the example in their respecting folder under `src/example/projects`.

**Comment by AruXc** [comment]
Thank a lot, does it support model nested object now?I didn't saw in the example.Radios seem can't
responsive with nested model.

**Comment by lionel-bijaoui** [comment]
@AruXc It is a bug, should be fixed with #532

**Comment by zoul0813** [comment]
@AruXc or @lionel-bijaoui Can we close this?

**Comment by AruXc** [comment]
@zoul0813  sure!
