### ISSUE TITLE
Documentation is unavailable since 10/14/2018

### ISSUE THREAD

**Issue by kahunacoder** [vue-generators/vue-form-generator#517]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  * [x] bug report
  * [ ] feature request
  * [ ] support request => Please do not submit support request here, see note at the top of this template.

- **Do you want to request a _feature_ or report a _bug_?**
Report a bug
* **What is the current behavior?**
Server not found
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://jsfiddle.net/ or similar (you can use this template as a starting point: https://jsfiddle.net/icebob/0mg1v81e/).
https://icebob.gitbooks.io/vueformgenerator/content/
* **What is the expected behavior?**
View Documents
- **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
N/A
  * Version: [2.X.X | 3.0.0-beta.X]
  * Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  * Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]
N/A
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by lionel-bijaoui** [comment]
@kahunacoder Thanks for the heads up !
[downforeveryoneorjustme](https://downforeveryoneorjustme.com/icebob.gitbooks.io) say it is down, but I can access it. WTF ?
@icebob Any clues ?

**Comment by zoul0813** [comment]
https://icebob.gitbooks.io/vueformgenerator/content/ is working for me as well.

And https://downforeveryoneorjustme.com/icebob.gitbooks.io says "its just me, its up".

It was probably just a temporary issue with gitbooks.io, outside of our control.

**Comment by kahunacoder** [comment]
It's working for me too now. It was down all day yesterday so I reported it when it was down today. I like that url downforeveryoneorjustme.com I would of reported it yesterday if I'd known about that url.
