### ISSUE TITLE
deep model won't work

### ISSUE THREAD

**Issue by serverfire** [vue-generators/vue-form-generator#542]
* **I'm submitting a bug**

* **What is the current behavior?**

the app won't work with deep model passing to label or input

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

this is the version without bug 
https://jsfiddle.net/9ody3m2g/

this is a version with the bug

https://jsfiddle.net/1bo0pvad/1/

* **What is the expected behavior?**
showing the data from a model in the input
* **Please tell us about your environment:**

  * Version: 2.3.1 
  * Browser: all

**Comment by zoul0813** [comment]
Fixed in #535
