### ISSUE TITLE
GitBook Access

### ISSUE THREAD

**Issue by zoul0813** [vue-generators/vue-form-generator#543]
@icebob or @lionel-bijaoui do either of you have access to the GitBooks account?

I'd like to start looking into cleaning up the documentation hosted there as it's pretty far behind at the moment.

I've setup a new GitBooks organization called "vue-generators" and was planning to migrate all of the existing documentation over to that, and making the documentation public via a GitHub repo (ie; vue-generators/vfg-docs) so it can be updated by the community more easily, as well as made available offline.

**Comment by icebob** [comment]
What is your gitbook username?

**Comment by zoul0813** [comment]
Same as GitHub, should be zoul0813 (signed up with GitHub SSO)

**Comment by icebob** [comment]
Btw, the book is on https://legacy.gitbook.com

**Comment by zoul0813** [comment]
higginsd at zoulcreations dot com is the email

**Comment by icebob** [comment]
Done.

**Comment by zoul0813** [comment]
thanks
