### ISSUE TITLE
Disabling specific radio options

### ISSUE THREAD

**Issue by Anoesj** [vue-generators/vue-form-generator#551]
I'm submitting a feature request.

I ran into some behavior I didn't expect in radios fields. It seems logical that setting `disabled: true` on a single option would result in `disabled="disabled"` on that particular option. However, options are only disabled when the whole radios field is disabled. I looked at fieldRadios.vue and to me it seems like the most simple solution would be to change this:
```vue
<template lang="pug">
	.radio-list(:disabled="disabled", v-attributes="'wrapper'")
		label(v-for="item in items", :class="{'is-checked': isItemChecked(item)}", v-attributes="'label'")
			input(:id="getFieldID(schema)", type="radio", :disabled="disabled", :name="id", @click="onSelection(item)", :value="getItemValue(item)", :checked="isItemChecked(item)", :class="schema.fieldClasses", :required="schema.required", v-attributes="'input'")
			| {{ getItemName(item) }}
```
into this:
```vue
<template lang="pug">
	.radio-list(:disabled="disabled", v-attributes="'wrapper'")
		label(v-for="item in items", :class="{'is-checked': isItemChecked(item), 'is-disabled': disabled || item.disabled}", v-attributes="'label'")
			input(:id="getFieldID(schema)", type="radio", :disabled="disabled || item.disabled", :name="id", @click="onSelection(item)", :value="getItemValue(item)", :checked="isItemChecked(item)", :class="schema.fieldClasses", :required="schema.required", v-attributes="'input'")
			| {{ getItemName(item) }}
```

This makes sure that a radio option is disabled whenever its parent is disabled entirely *and* whenever that particular option is disabled itself.

Example (expected behavior after option label):
https://jsfiddle.net/Anoesj/qd8fv430/

Version: 2.3.2

**Comment by Anoesj** [comment]
@zoul0813 Absolutely, great work! I was hoping this would arrive in v3, but this is even better :-)

**Comment by Anoesj** [comment]
@zoul0813 One minor improvement would be adding a class "is-disabled" to labels belonging to disabled radio inputs. This allows for easy radio styling. For example, right now, we can't put opacity: 0.4 on the label text when the radio input is disabled.

**Comment by zoul0813** [comment]
Sounds like a good request - I’ll see what I can do, PR’s welcome.

I’d suggest using a more generic class like “disabled” ...

**Comment by Anoesj** [comment]
I'll see if I can make some time to work on this, little bit busy though. I would still go for "is-disabled" since "is-checked" is already being used.
