### ISSUE TITLE
Dynamic Functions added to schema keys can't see model or schema context

### ISSUE THREAD

**Issue by DelfsEngineering** [vue-generators/vue-form-generator#568]
* [x] feature request

Feature Request

* **What is the current behavior?**
When replacing many field schema keys with functions I don't have access to the `schema` or `model, I have been binding the VFG to the `window` so I can reference needed model attributes etc. 

If there is not a good way to do this, could we add the schema to the `this` context so that functions that are dynamically added can see the model and schema?

The window binding method was ok for a single instance, but for multiple instances it fails.

* **What is the expected behavior?**
in function or function getters that are attached to schema keys (dynamic labels etc) it would be good to be able to see the rest of the schema and model.

**Comment by zoul0813** [comment]
Can you provide a sample of the functions you’re referring too?

**Comment by DelfsEngineering** [comment]
@zoul0813 sure:
my use case basically generates entire web apps from schema and at the core is VFG !!(www.fmbetterforms.com if you want a better background.)

Users can add their own calc equations to the schema and before render, I convert these calcs to functions or values with getters so that VFG and any other components can read them.

This is an example:
This schema:
```
{
  "inputType": "text",
  "label_calc": " 'Hello Mr. ' + model.nameLast +'Tell us your first name:' ",
  "model": "nameFirst",
  "type": "input"
}
```
Gets converted on the fly to this: ( and to get model within the function I reference window.mySchema.model etc
(It is actually an object with a getter that has the function, since most keys are not looking for functions, but basically you get the idea I hope)

```
{
  "inputType": "text",
  "label": function() {
    return "'Hello Mr. ' + model.nameLast +'Tell use your first name'"
  }
  "model": "nameFirst",
  "type": "input"
}
```
And this would create a dynamic reactive label. This works great for single instances.
So Basically within my getter function I need to be able to see things outside the scope of the component. because I need to reference the VFG that this is within. I could attach multiple VFG schema's to `window` in an array but I still will not know which one is which from within the getter.

For reference I am doing something like this
```
      Object.defineProperty(object, key, {
        enumerable: true,
        get() {
          return function(){  "'Hello Mr. ' + model.nameLast +'Tell use your first name'" }
        }
      });
// where object is the schema above and key is `label` 
```
I am trying to simplify the problem so have left some things out. From within the function, the `this` object is the form schema first stated above. So I want to pass things into it there. Perhaps a mixin or global plugin ?

Much thanks for help with this.

**Comment by zoul0813** [comment]
Not sure how best to solve this problem, but I’ll take a look.  I’ll need to write up some sample code (a working example project would be great, if you have the time) and see this in action... unfortunately, this isn’t a use caseive come across yet.

In the mean time, you could inject a reference to the VFG and Model objects into the schema ... so schema.vfg and schema.model are just references to the correct objects.  Then this.vfg and this.model should work.

Attach these to the schema when you attach the getter functions, and it should give you what you need and you’ll be able to have context without polluting the global scope.

**Comment by DelfsEngineering** [comment]
Thanks @zoul0813 Dave, I added a reference to the top object to each node that has a function and that works out well.
