### ISSUE TITLE
Email field validation behavior change or offer alternative option

### ISSUE THREAD

**Issue by guzun** [vue-generators/vue-form-generator#580]
* **I'm submitting a feature request**

- **Do you want to request a _feature_ or report a _bug_?**
I'd like to request a feature for the email field validation.

* **What is the current behavior?**
Currently as soon as the user starts typing the email address, the validation triggers and the error message shows up. That is a bit frustrating for the users.

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://jsfiddle.net/ or similar (you can use this template as a starting point: https://jsfiddle.net/icebob/0mg1v81e/).

* **What is the expected behavior?**
Would it be possible to do the validation for the email field on submit only ? Or at least to not trigger it before the submit button is pressed for the first time (most real life forms have a submit button)

- **What is the motivation / use case for changing the behavior?**
Users are finding that validation message confusing and distracting when they first are filling up a form.

* **Please tell us about your environment:**

  * Vue Form Generator Version: [2.2.2.]
  * Browser: [all ]

**Comment by zoul0813** [comment]
Please refer to the documentation.

You can disable validation on change, or add a denounce time to validation on all or explicit fields.

You can also add a submit button outside of VFG, or as a field within VFG.  You can either trigger validation manually with the “validate” method of the VFG component (refer to Vue “$refs”), or by enabling validateOnSubmit with a VFG submit.

**Comment by guzun** [comment]
Thank you!
Totally missed the validateDebounceTime.
