### ISSUE TITLE
What is wrong in my vueMultiSelect

### ISSUE THREAD

**Issue by Atiladanvi** [vue-generators/vue-form-generator#583]
When i try remove the tag added in my multi select the options multiplies in my input automaticaly.
I get this reference in doc-site
![image](https://user-images.githubusercontent.com/11599205/51876324-fe248580-2346-11e9-9d1f-460c0d6173c4.png)

```javascript 
{
    type: "vueMultiSelect",
    model: "cid10",
    label: "cid10",
    placeholder: "Busque uma doença",
    required: true,
    validator: VueFormGenerator.validators.required,
    selectOptions: {
        multiple: true,
        key: "code",
        label: "name",
        searchable: true,
        taggable: true,
        tagPlaceholder: "Adicione o código",
        onNewTag: function(newTag, id, options, value) {
            const tag = {
                name: newTag,
                code: newTag.substring(0,2) + Math.floor((Math.random() * 10000000))
            };
            options.push(tag);
            value.push(tag);
        }
    },
    onChanged: function(model,newVal,oldVal,field) {
        console.log('@tag:', newVal);
    },
    values: [

    ]
}
```

**Comment by chris-jones** [comment]
@Atiladanvi Did you find your solution?

I had a similar issue that was related to the version of Vue-Multiselect I was using (i.e. the latest version) however, downgrading to an earlier version (2.0.0-beta) fixes the issue but brings about another issue. There seems to be an incompatibility issue between the beta version of vue-multiselect and the latest vue-generator though.

**Comment by a21ns1g4ts** [comment]
Post your code.

**Comment by chris-jones** [comment]
I've actually found out the solution and I think the documentation needs updating, but in essence, the property "trackBy" needs to be added to selectOptions, when using JSON objects as values.

**Comment by a21ns1g4ts** [comment]
You can submit a pull request about that.
