### ISSUE TITLE
Unknown custom element: <field-multiselect>

### ISSUE THREAD

**Issue by hightechguy** [vue-generators/vue-form-generator#585]
* **I'm submitting a ...**
  * bug report

* **What is the current behavior?**

`[Vue warn]: Unknown custom element: <field-multiselect> - did you register the component correctly?`

* **What is the expected behavior?**
Display the drop-down

* **Please tell us about your environment:**

  * Version: [2.X.X | 3.0.0-beta.X]
  * Browser: [Chrome 71]
  * Language: [ES6/7 | ES5]

```javascript
// App.vue
<template>
  <div id="app">
    <vue-form-generator :schema="schema" :model="model" :options="formOptions"></vue-form-generator>
  </div>
</template>


<script>
import Vue from 'vue';
import VueFormGenerator from "vue-form-generator";
import Multiselect from "vue-multiselect";


import 'vue-multiselect/dist/vue-multiselect.min.css';

Vue.use(VueFormGenerator);
Vue.component('multiselect', Multiselect)

export default {
  data: function() {
    return {
      schema : {
        fields: [
          {
            type: "multiselect",
            model: "library",
            label: "Libraries",
            selectOptions: {
              multiple: true,
              key: "name",
              label: "language",
              searchable: true,
            },
            values: [
              {
                name: "Vue.js",
                language: "JavaScript",
              },
              {
                name: "Kuku",
                language: "PHP",
              },
              {
                name: "Dudu",
                language: "Ruby",
              },
            ],
          }
        ]
      },
      model: {},
      formOptions: {
        validateAfterLoad: true,
        validateAfterChanged: true
      }
    }
  }
}
</script>
```

**Comment by zoul0813** [comment]
not entirely sure I understand what your code is doing, but if you want to use the multiselect component, please refer to the docs: https://vue-generators.gitbook.io/vue-generators/fields/optional_fields/vuemultiselect 

You'll need to make sure that vueMultiSelect is installed properly, then use the correct VFG field type name ... which is `vueMultiSelect`, not `multiselect`.

**Comment by hightechguy** [comment]
@zoul0813 Thanks for your time! 
I'm just trying to create a schema with vue-multiselect demo. 

I've followed your advice: double checked the component installation and renamed `multiselect` with `Multiselect`:

```
<template>
  <div id="app">
    <vue-form-generator :schema="schema" :model="model" :options="formOptions"></vue-form-generator>
  </div>
</template>


<script>
import Vue from 'vue';
import VueFormGenerator from "vue-form-generator";
import vueMultiSelect from "vue-multiselect";

import 'vue-multiselect/dist/vue-multiselect.min.css';

Vue.use(VueFormGenerator);
Vue.component('vueMultiSelect', vueMultiSelect)

export default {
  data: function() {
    return {
      schema : {
        fields: [
          {
            type: "vueMultiSelect",
            model: "library",
            label: "Libraries",
            selectOptions: {
              multiple: true,
              key: "name",
              label: "language",
              searchable: true,
            },
            values: [
              { name: "One", language: "JS"},
              { name: "Two", language: "PHP"},
              { name: "Tree", language: "Ruby"}
            ],
          }
        ]
      },
      model: {},
      formOptions: {
        validateAfterLoad: true,
        validateAfterChanged: true
      }
    }
  }
}
</script>
```

Is still fails with
`Uncaught TypeError: Cannot read property 'fieldVueMultiSelect' of undefined
    at eval (main.js?56d7:8)
    at Module../src/main.js (app.js:1987)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at Object.0 (app.js:2000)
    at __webpack_require__ (app.js:724)
    at app.js:791
    at app.js:794`

The link to http://monterail.github.io/vue-multiselect/ on https://vue-generators.gitbook.io/vue-generators/fields/optional_fields/vuemultiselect is broken. I guess it should be https://github.com/shentao/vue-multiselect?

**Comment by zoul0813** [comment]
Follow the correct instructions for multi select, register it as “multiselect”, and use the correct schema type from the docs

**Comment by zoul0813** [comment]
The schema does not use the same name as the registered component, it’s just a dependency of the VFG component

**Comment by hightechguy** [comment]
I'd love to. Can you point me to the docs please?
The link to vueMultiSelect
<https://github.com/vue-generators/vue-form-generator-docs/tree/177626599980e45a1eff5f61cb55963386a1c6d8/vuemultiselect.md>
 on https://vue-generators.gitbook.io/vue-generators/installation is broken
too.

Thanks!

**Comment by zoul0813** [comment]
Use the docs for whatever version of the package you downloaded - I don’t know which package you installed.  

Probably - https://github.com/shentao/vue-multiselect
