### ISSUE TITLE
Overriding formGroup template

### ISSUE THREAD

**Issue by fedeisas** [vue-generators/vue-form-generator#586]
Perhaps this is a more general Vue question, but I've been battling with this for hours. Is there any way to replace the template un `formGroup` to change how validation is rendered to match Bootstrap 4?

**Comment by zoul0813** [comment]
Have you look into the various properties available for setting the html tag, and css classes of some elements?

Unfortunately, you can’t change all of the markup, but you do have access to tag and css class names at varying levels.
