### ISSUE TITLE
A 'displayOnly' option

### ISSUE THREAD

**Issue by PeterC66** [vue-generators/vue-form-generator#588]
This is a **feature request**, or maybe advice on how I can achieve what I want. I love vfg and am building parts of my system around it. 

In my application there are sets of (geographic) data managed by different users, and each user are able to specify the fields in each of their own data sets. At the moment these specifications are in vfg format (schema), or csv which I will be able to compile into vfg format. (It will be even better when we have a schema generator they can use.) They will then be able to enter/edit their data sets in a vfg-based modal I have developed. So far so good.

**What I would now like** is for people to be able to hover over points on a map and see the data displayed in a neat way based on its vfg schema. I do this now in a hard-coded way, but what I would like to be able to do is provide a vfg-based component that just displays the data (no editing, validation etc., with a compact styling).

You can see what I have in mind in [my prototype system](https://www.mapping4ops.org/M4OPS?&OPS=HNB&Layer1=1910%20Valuation&Layer2=1910%20Valuation&Lon=1.1301410&Lat=51.3689085&Zoom=16&Splash=OneSlider). (When the blue features have loaded you can hover over them to see the data.)

If this could not be available in vfg itself I plan to work on a routine that takes a vfg specification and uses it to prepare a display in the formats I want.

**Comment by zoul0813** [comment]
Have you looked into the VFG label component?

**Comment by PeterC66** [comment]
Thanks. Not sure what you mean by the VFG label component.
I know fields have a 'label' property, and there is a 'label' fieldtype - I presume you are meaning the former.

**Comment by zoul0813** [comment]
Correct - check here, https://vue-generators.gitbook.io/vue-generators/fields/core-fields/label

**Comment by PeterC66** [comment]
I'll try and develop something like I envisage - showing the label property and formatted (model) value for each field in a compact format.

**Comment by zoul0813** [comment]
Sounds good - if you feel it would be usable to others, please create a github repo and let us know... happy to add it to the readme/docs as a third-party component
