### ISSUE TITLE
Docs for dateTimePicker request

### ISSUE THREAD

**Issue by izzyreal** [vue-generators/vue-form-generator#589]
I don't get what is required to get the dateTimePicker field type working. For someone relatively new to frontend dev, the requirements are hard to understand. I keep getting ```Bootstrap datetimepicker library is missing. Please download from https://eonasdan.github.io/bootstrap-datetimepicker/ and load the script and CSS in the HTML head section!``` no matter what I do.

Docs for this field are scattered across github issues, and we're being referred to http://eonasdan.github.io/bootstrap-datetimepicker which has nothing about how to use it in Vue. I also don't understand how to recreate https://jsfiddle.net/0mg1v81e/148/ in my own project.

Maybe the vfg docs could outline some simple steps:
* Which packages need to be added
* Which imports need to take place in your .vue file's `<script></script>` section

**Comment by zoul0813** [comment]
Please look at: https://github.com/vue-generators/vue-form-generator-docs/blob/master/fields/datetime.md 

These are external dependencies, and should be made globally available to your application, so that the VFG component can access them.

**Comment by timoteo7** [comment]
for Vue.js install:
`npm install vue-bootstrap-datetimepicker`

and import:
```
import datePicker from 'vue-bootstrap-datetimepicker';
import 'pc-bootstrap4-datetimepicker/build/css/bootstrap-datetimepicker.css';
```
