### ISSUE TITLE
Document events and when they occur

### ISSUE THREAD

**Issue by networkimprov** [vue-generators/vue-form-generator#593]
There should be documentation of all events which VFG can $emit on a new page in this section:

https://vue-generators.gitbook.io/vue-generators/component

**Comment by zoul0813** [comment]
@networkimprov thanks, didn't realize these were missing.  I've added information about the events to the docs.  Please feel free to issue a PR for any corrections.

**Comment by networkimprov** [comment]
Thanks!

Hm, these pages are now empty
- https://vue-generators.gitbook.io/vue-generators/component/schema
- https://vue-generators.gitbook.io/vue-generators/component/model
- https://vue-generators.gitbook.io/vue-generators/component/options

I think the links in main text of this page used to link to the above, but now they don't?
https://vue-generators.gitbook.io/vue-generators/component

**Comment by zoul0813** [comment]
oops - I screwed up the links, I'll correct that shortly.  I moved all the component related docs into a component folder, as they were all in the doc root originally.

**Comment by zoul0813** [comment]
This should be fixed, I'm just waiting for GitBook to run it's auto-update.  I also added a reference to the docs repo's develop branch, so you should see a version selector at the top now ... you can see the fixes in the develop version.

**Comment by networkimprov** [comment]
Component docs look good.

The version selector gives "1.0.0" which is unexpected...

**Comment by zoul0813** [comment]
Yeah, unfortunate side effect of enabling the versioning ... I’ll see if I can get that to match the current release or use an alternative phrase like “current”.

**Comment by networkimprov** [comment]
model-updated docs seem incorrect. In 2.3.4, the schema argument has a model string, whereas docs say:

>schema is a reference to the individual field schema. schema will only contain the individual field data, and not the full schema
