### ISSUE TITLE
compatibility with element-ui

### ISSUE THREAD

**Issue by ehsanbagherzadegan** [vue-generators/vue-form-generator#596]
Hi, thanks for amazing package ,if you can replace simple input by element-ui i think this package is the best.
best regards.

**Comment by zoul0813** [comment]
Support for third party UI frameworks can be provided as a separate package.

We won’t be adding any specific UI framework dependencies to VFG Core.

Feel free to create a compatible plugin for VFG and submit a PR to the README and Docs with a link to the plugins repo.
