### ISSUE TITLE
Add schema.createEmptyObject() or indicate empty in event

### ISSUE THREAD

**Issue by networkimprov** [vue-generators/vue-form-generator#597]
If VFG gets an empty model `{}`, it adds fields to the model even if the user undoes their changes to the form, e.g. a string field becomes `{s: ''}`. So there is no way to take an action when a model becomes empty.

__Options__

- A function to create an empty model: `var m = schema.createEmptyObject(schema)`. The resulting object would contain each schema field with the value that results from setting and unsetting its form widget.

(EDIT:)

- Provide "isEmpty" argument on the model-updated event. That would allow you to delete the field from the model.

- Emit a "model-empty" event.

**Comment by zoul0813** [comment]
What is the purpose and/or use case here?

**Comment by networkimprov** [comment]
An app that stores form state as inputs occur. When the model becomes empty, we must drop that form state instead of storing it.

**Comment by zoul0813** [comment]
There’s the model-updated event to track changes - if the value is empty, remove it?

In this case, you would pass VFG a copy of your stored model data, then update the master on model-updated as needed.

I have similar logic in one of my apps, keeping data in Vue Store, and update it when VFG triggers model-updated, I can reset and cancel by just copying the Store data over the VFG model.

**Comment by networkimprov** [comment]
The schemas are user-supplied, so I can't hard-code an empty model object for a schema; hence the request for schema.createEmptyObject()

How would you tell that the model-updated event value is "empty"? For strings it's `''`, but other types?

**Comment by zoul0813** [comment]
VFG relies on lodash, so try _.isEmpty?

**Comment by networkimprov** [comment]
Is lodash accessible via the VueFormGenerator object; I don't see it there...

**Comment by networkimprov** [comment]
Oh, `_` is a top-level object, found it.

Is it official that isEmpty() returns true for every field type?

Could you add this to the event docs?
"If `_.isEmpty(newVal)` returns true, the field may safely be removed from the model."

**Comment by zoul0813** [comment]
Clearly listed in package.json

import _ from “lodash”;

**Comment by networkimprov** [comment]
Sorry, I had these other Q's:

Is it official that isEmpty() returns true for every field type?

Could you add this to the event docs?
"If `_.isEmpty(newVal)` returns true, the field may safely be removed from the model."

**Comment by networkimprov** [comment]
__EDIT:__ _.isEmpty() returns true for Number values, so that's not a solution. Can you reopen this?

Sorry, I had these other Q's:

Is it official that isEmpty() returns true for every field type?

Could you add this to the event docs?
"If `_.isEmpty(newVal)` returns true, the field may safely be removed from the model."

**Comment by zoul0813** [comment]
If you need support with Lodash, please visit their GitHub repo, and/or StackOverflow

**Comment by networkimprov** [comment]
Based on https://github.com/lodash/lodash/issues/496, I came up with this, but I fear that it's brittle:
```
methods: {
   onModelUpdate: function(iVal, iField) {

      // a safe test would be specific to field type
      // this one is not verified for all field types
      if (iVal !== true && !_.isFinite(iVal) && _.isEmpty(iVal))
         delete this.formState[iField];
      ...
   },
```

If I wrote anything to irritate you, my sincere apology.
