### ISSUE TITLE
Component to display fields

### ISSUE THREAD

**Issue by PeterC66** [vue-generators/vue-form-generator#602]
Following on from my request #588 I have created a draft public package ['vfg-display-fields'](https://github.com/PeterC66/vfg-display-fields).  This displays the fields of an object - using a vfg schema if provided.

I am using it in developing my mapping system, where data structures are flexible and will be able to be set up by users using vfg, I publish it in case it is of interest to others.

I am fairly new to the Vue.js, git, npm etc ecosystem, so I am sure there is lots that can be improved. (Please comment in [that repo](https://github.com/PeterC66/vfg-display-fields/issues).)

Could there be a reference to vfg-display-fields from vue-form-generator?

**Comment by zoul0813** [comment]
you are welcome to submit a PR request adding a link to the repo to the README, as well as to the [vue-form-generator-docs](https://github.com/vue-generators/vue-form-generator-docs) repo

Perhaps your [demo on CodeSandbox](https://codesandbox.io/embed/ykpj1jpxvv?fontsize=14&view=preview) could show toggling between the "read only" view your component provides and an "edit" mode by having VFG integrated into the demo ... have an edit button or something toggle between them, to show a nice use-case for VFG users?

**Comment by PeterC66** [comment]
Thanks.  I have changed the demo as you suggested.  I will do PRs soon.

**Comment by zoul0813** [comment]
looks great - thanks for the component, I'm going to close this issue and will approve the PR for the docs when it comes in

**Comment by PeterC66** [comment]
Sorry but for various reasons I have decided to retire (again), and stop all my Vue.js developments. [vfg-display-fields](https://github.com/PeterC66/vfg-display-fields) is nearly ready for its first proper publish, and just needs setting up to build an ES5 version.  If anyone would like to take it on I would be very happy for them to do so. 

I wish you well with vfg, as I loved working with it. I never got round to doing a PR for you.
