### ISSUE TITLE
vue form generator using server schema data and form wizard

### ISSUE THREAD

**Issue by bhavesh-786** [vue-generators/vue-form-generator#617]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  * [ ] bug report
  * [ ] feature request
  * [ ] support request => Please do not submit support request here, see note at the top of this template.

- **Do you want to request a _feature_ or report a _bug_?**

* **What is the current behavior?**

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://jsfiddle.net/ or similar (you can use this template as a starting point: https://jsfiddle.net/icebob/0mg1v81e/).

* **What is the expected behavior?**

- **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  * Version: [2.X.X | 3.0.0-beta.X]
  * Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  * Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bhavesh-786** [comment]
Hello, 
I am trying to generate multistep form using form-wizard + vue-form-generator but I am having issue in vue validation. 

<form-wizard @on-complete="onComplete" validate-on-back
                     ref="wizard"
                     :start-index.sync="activeTabIndex"
                     shape="circle" color="#20a0ff" error-color="#ff4949" v-if="html != 0">
            <tab-content title="Personal details" v-for="(wiz, index) in html" :key="index" icon="icon icon-user" :before-change="validateFunction(index)">

                <vue-form-generator :model="model"
                                    :schema="wiz"
                                    :options="formOptions"
                                    :ref="index">
                </vue-form-generator>
                
            </tab-content>
            <tab-content title="Last step"
                         icon="icon icon-check">
                <h4>Your json is ready!</h4>
                <div class="panel-body">
                    <pre v-if="model" v-html="prettyJSONModel(model)"></pre>
                </div>
            </tab-content>
        </form-wizard>

json data 

{"firstTabSchema":{
                    "groups": [
                        {
                            "legend": "User Details",
                            "fields": [{
                                "type": "input",
                                "inputType": "text",
                                "label": "First name",
                                "model": "firstName",
                                "required": true,
                                "styleClasses": "col-xs-6"
                            },
                                {
                                    "type": "input",
                                    "inputType": "text",
                                    "label": "Last name",
                                    "model": "lastName",
                                    "required": true,
                                    "styleClasses": "col-xs-6"
                                },
                                {
                                    "type": "input",
                                    "inputType": "text",
                                    "label": "Email",
                                    "model": "email",
                                    "required": true,
                                    "styleClasses": "col-xs-12"
                                }
                            ]
                        }]
                },
                "secondTabSchema":{
                    "groups": [
                        {
                            "legend": "User Details",
                            "fields": [
                                {
                                    "type": "input",
                                    "inputType": "text",
                                    "label": "Street name",
                                    "model": "streetName",
                                    "required": true,
                                    "styleClasses": "col-xs-9"
                                },
                                {
                                    "type": "input",
                                    "inputType": "text",
                                    "label": "Street number",
                                    "model": "streetNumber",
                                    "required": true,
                                    "styleClasses": "col-xs-3"
                                },
                                {
                                    "type": "input",
                                    "inputType": "text",
                                    "label": "City",
                                    "model": "city",
                                    "required": true,
                                    "styleClasses": "col-xs-6"
                                },
                                {
                                    "type": "select",
                                    "label": "Country",
                                    "model": "country",
                                    "required": true,
                                    "values": ["United Kingdom", "Romania", "Germany"],
                                    "styleClasses": "col-xs-6"
                                }
                            ]
                        }]
                }}

when I am rendering html befor-change it;s calling by default and even if I click on next button also calling 2 time please help me for this.
Thank You

**Comment by zoul0813** [comment]
Please use stackoverflow and properly format your request.

**Comment by bhavesh-786** [comment]
Hello,

I am using this example please check this link 
https://jsfiddle.net/3ordn7sj/5/

if I'am going to add :before-change="validateFirstTab(index)" inside  <tab-content> then it's showing me error and not able to do validation,

> Error

> TypeError: Cannot read property 'validate' of undefined
    at wn.validateFirstTab ((index):146)
    at eval (eval at Ya (vue.min.js:6), <anonymous>:3:300)
    at wn.vt [as _l] (vue.min.js:6)
    at wn.eval (eval at Ya (vue.min.js:6), <anonymous>:3:157)
    at wn.e._render (vue.min.js:6)
    at wn.r (vue.min.js:6)
    at fn.get (vue.min.js:6)
    at new fn (vue.min.js:6)
    at vue.min.js:6
    at wn.$mount (vue.min.js:6)

**Comment by zoul0813** [comment]
This does not appear to be a VFG issue and sounds like it is a problem with VueFormWizard.

Please use StackOverflow to get assistance with this.
