### ISSUE TITLE
Is there possibility to create an custom field as a table of multiple column and rows 

### ISSUE THREAD

**Issue by bhavesh-786** [vue-generators/vue-form-generator#621]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  * [ ] bug report
  * [x] feature request
  * [x] support request => Please do not submit support request here, see note at the top of this template.

- **Do you want to request a _feature_ or report a _bug_?**

* **What is the current behavior?**

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://jsfiddle.net/ or similar (you can use this template as a starting point: https://jsfiddle.net/icebob/0mg1v81e/).

* **What is the expected behavior?**

- **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  * Version: [2.X.X | 3.0.0-beta.X]
  * Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  * Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bhavesh-786** [comment]
I want to create a custom field of type table to be utilize to show multiple rows of information in the process of submitting a form which build using VFG. 
Is that practical  or can be done with custom fields.
Please advice.
Thank You

**Comment by UBK-RE** [comment]
Validation could be a problem.

**Comment by zoul0813** [comment]
Can definitely be done, fairly sure there’s one or more custom fields referenced in the docs or readme as separate projects which add arrays... which would be the base of a table field.

As for validation, you’d just have to implement a way to loop each record and then validate the content internally... you could call the VFG validation methods (they’re public) if you want.

One possible solution could also be to nest a VFG form inside of the custom field... and each row could be a separate inline VFG form...which would allow you the ability to reuse the VFG schema to define your table row schema...

**Comment by zoul0813** [comment]
not an issue - support request
