### ISSUE TITLE
Error in nextTick: "TypeError: Cannot read property 'validate' of undefined"

### ISSUE THREAD

**Issue by kevinkiel** [vue-generators/vue-form-generator#637]
When I set validateAfterLoad: true inside the options I'm get the following error (this happens when I mounted the component for the first time):

Error in nextTick: "TypeError: Cannot read property 'validate' of undefined"

Console error:
TypeError: Cannot read property 'validate' of undefined
    at VueComponent.validate (vfg.js?4309:7)
    at eval (vfg.js?4309:7)
    at n (vfg.js?4309:7)
    at r (vfg.js?4309:7)
    at VueComponent.validate (vfg.js?4309:7)
    at VueComponent.eval (vfg.js?4309:7)
    at Array.eval (vue.runtime.esm.js?2b0e:1980)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1906)

**Comment by zoul0813** [comment]
Please provide a jsFiddle

**Comment by zoul0813** [comment]
I assume you figured out the problem then?

**Comment by kevinkiel** [comment]
> I assume you figured out the problem then?

Yeah I'm sorry I didn't reply

There was a problem in register the component I used

const fields = require.context('.', false, /\.vue$/)

fields.keys().forEach(fileName => {
  let id = fileName.replace('./', '').replace('.vue', '')
  Vue.component(id, fields(fileName))
})

in stead of 

const fields = require.context('.', false, /\.vue$/)

fields.keys().forEach(fileName => {
  let id = fileName.replace('./', '').replace('.vue', '')
  Vue.component(id, fields(fileName).default)
})
