### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by imtag** [vue-generators/vue-form-generator#638]
Cannot read property 'toLowerCase' of undefined
![1565254688228](https://user-images.githubusercontent.com/20496148/62689594-b79e9a80-b9fd-11e9-8718-601d582f57e8.jpg)

vue: 2.6.10
vue-form-generator: 2.3.4

**Comment by zoul0813** [comment]
Please follow the issue submission guidelines

Closing this for now
