### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by OkaSroka** [vue-generators/vue-form-generator#659]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  * [x] bug report
  * [ ] feature request
  * [ ] support request => Please do not submit support request here, see note at the top of this template.

- **Do you want to request a _feature_ or report a _bug_?**

* **What is the current behavior?**

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://jsfiddle.net/ or similar (you can use this template as a starting point: https://jsfiddle.net/icebob/0mg1v81e/).

* **What is the expected behavior?**

- **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  * Version: [2.X.X | 3.0.0-beta.X]
  * Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  * Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by OkaSroka** [comment]
https://jsfiddle.net/zdh8ot3c/4/
I am getting error for good patterns in regular expresion
Error:
"(index):1 Pattern attribute value ^[^d±!@£$%^&*_+§¡€#¢§¶•ªº«\/<>?:;|=.,{}[]ÄäÖöÜüẞß]{1,}$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^[^d±!@£$%^&*_+§¡€#¢§¶•ªº«\/<>?:;|=.,{}[]ÄäÖöÜüẞß]{1,}$/: Lone quantifier brackets"

you can test it: https://www.regextester.com/97999

**Comment by zoul0813** [comment]
It’s not valid, you didn’t escape the {}[] characters

**Comment by OkaSroka** [comment]
@zoul0813 
How it should look like then??
because it is working for me in html pattern https://www.w3schools.com/tags/att_pattern.asp
but not in vue-form-generator
Can you help me?

**Comment by zoul0813** [comment]
It needs to be a valid JavaScript regular expression.

The regex validator in VFG just passes the expression to the RegExp class, here’s the validators code

```
if (!isNil(field.pattern)) {
			let re = new RegExp(field.pattern);
			if (!re.test(value)) {
				return [msg(messages.invalidFormat)];
			}
		}
```

https://github.com/vue-generators/vue-form-generator/blob/master/src/utils/validators.js

**Comment by OkaSroka** [comment]
Thanks @zoul0813 now it is working: https://jsfiddle.net/kawjgrLh/1/
