### ISSUE TITLE
Schema input onChange Issue

### ISSUE THREAD

**Issue by santhoshbalusamy** [vue-generators/vue-form-generator#660]
https://github.com/vue-generators/vue-form-generator/blob/721a4eebbde77040a1318e60aa9ef21229bbcf99/src/fields/core/fieldInput.vue#L10

I am not able to use the onChange function which I mentioned above in the schema

Is there any onBlur event is emitted as like onChanged event?
I tried to use the onChange function to define in the schema, but vue is not picking it up.
I need an event that should emit once I focus out (onBlur) of the element

eg: {
        type: "input",
        inputType: "text",
        label: "Name",
        id: 'user_name',
        model: "name",
        inputName: 'name',
        placeholder: "User's name",
        **onBlur: function(model, field) {
          //do the operation
        }**
}

@zoul0813 any leads?

**Comment by zoul0813** [comment]
We do not emit any blur events to my knowledge.

You can create a quick custom field that emits a blur event and have it look for scheme.blur

Just duplicate whatever fields you’re using from VFG and add the blur logic to it to create a custom field
