### ISSUE TITLE
Add multiple fields in one row

### ISSUE THREAD

**Issue by cherrycoding** [vue-generators/vue-form-generator#678]
Hi, how can I add multiple fields in one row?
E.g. street | house no | door
zipcode | city
Is there any function maybe with an additional schema field "row" to group the fields in rows?
Thanks

**Comment by DelfsEngineering** [comment]
This is a CSS thing.
Eg, if you are using Boostrap 3, 
```
"styleClasses" : "col-md-3"
```
In each element would render 4 elements per row.

c
