### ISSUE TITLE
Dead repository ?

### ISSUE THREAD

**Issue by Mikaleb** [vue-generators/vue-form-generator#702]
Is the repo dead ?

**Comment by DelfsEngineering** [comment]
No but there certainly has been little movement. I would be happy to help to keep things moving. 
There are a number of key features we need but have been holding of forking as long as possible.

**Comment by vesper8** [comment]
@DelfsEngineering why do you answer "no" I wonder? The last commit is over 2 years old now. How can this be anything but a dead repository then?

I had big hopes for v3 and actually used it for a while but I'd rather move to something that is actively maintained

**Comment by DelfsEngineering** [comment]
I mean there is little commit activity, true, but it is still in demand and at the core of my app. 

Personally I was hoping the maintainers would put out a request for others to help. 

If not we will fork ourselves. 

What are your suggestions @vesper8 ?

**Comment by vesper8** [comment]
I have no desire to fork and maintain this package. It's true that it is functional, specially the v3 branch. I think this project is very much dead though.. best to move on to something else.. or just accept it and keep using it.

I've identified a few possible alternatives.

https://github.com/jarvelov/vue-form-json-schema <-- this one seems the most promising IMO

https://github.com/ncform/ncform
https://github.com/GavinZhuLei/vue-form-making
https://github.com/JakHuang/form-generator
https://github.com/woai3c/vue-form-maker
https://github.com/formio/formio.js

**Comment by dflock** [comment]
No need to fork. If someone wants write access to this repo, and has a history of good work, then I think we can make that happen.

**Comment by DelfsEngineering** [comment]
@icebob @zoul0813  Thoughts?

**Comment by icebob** [comment]
Currently there is no active maintainer for this project.

**Comment by olfek** [comment]
Does this work with Vue 3 ?
